#!/bin/bash

# Multi opener.

set -e

. mutil.sh

temp=${PIPE_TEMP:-/tmp}

function usage() {
  cat <<EOF

  1: Multi purpose file opener

  Usage: 1 [options] FILES...

EOF
}

opts=()
bg=1
pipe=0
force_editor=0
pretty=0
use_vim=0
copy=0
no_zenlog=0
newdoc=0
noargs=0
mkpath=0
cbin=0
quiet=0
line=0
column=0
tee=0
force_new_window=0

#if ! is-interactive ; then
#  no_zenlog=1
#fi

# if (( $# == 0 )) ; then
#   noargs=1
# fi

eval "$(bashgetopt -u usage '
  w|wait           bg=0            # Wait until the editor returns.
  n|background     bg=1            # Don'\''t wait until the editor returns (default).
  e|force-editor   force_editor=1  # Disable smart file handling and force editor.
  p|pretty         pretty=1        # Pretty-print for XML/Json.
  d|no-pretty      pretty=0        # No pretty-print.
  N|newdoc         newdoc=1;force_new_window=1        # Open new timestamped doc.
  z|no-zenlog      no_zenlog=1     # Don'\''t use zenlog logfile to catch stdin input.
  pipe             pipe=1          # Read from stdin.
  stdin            pipe=1          # Read from stdin.
  t|tee            tee=1;pipe=1    # Read from stdin and also print on stdout.
  makepath         mkpath=1        # Make the directory.
  C|cbin           cbin=1          # Also open ~/cbin/
  q|quiet          quiet=1         # Set EE_QUIET=1
  l|line=i         line=%          # Open at a given line
  new-window       force_new_window=1 # Force new window
' "$@")"

args=( "$@" )
files=()

if (( ${ALT_MODE:-0} == 1 )) ; then
  case "$(select-menu '1: open/view normally' 'e: force edit')" in
    1)
      ;;
    e)
      force_editor=1
      ;;
    *)
      exit 1
  esac
fi


if (( $quiet )) ; then
    export EE_QUIET=1
fi

if (( $newdoc )) ; then
  doc="$(tasklog-file)"
  echo "$doc"
  files+=("$doc")
fi

if (( $cbin )) ; then
  # opts+=("--add" "$HOME/cbin")
  opts+=("$HOME/cbin/workspace.code-workspace")
fi

if (( ${#args} == 0 && ${#files} == 0 )) ; then
  if [[ -t 0 ]] ; then
    files+=("$HOME/work.txt")
  else
    pipe=1
  fi
fi

eat_stdin() {
  local out="$1"
  if (( $tee  )) ; then
    tee "$out"
  else
    cat >"$out"
  fi
}

if (( $pipe != 0 )) ; then
  if zenlog in-zenlog && (( ! $no_zenlog )) ; then
    byellow "Writing to current zenlog file..." | zenlog write-to-outer
    eat_stdin "$(zenlog logger-pipe)"
    log=$(zenlog history -n 1)
  else
    log="$temp/pipe-$(date8)-$$.log"
    byellow -n "Logging to: "
    echo $log
    eat_stdin $log
  fi

  args+=($log)
fi

# If the file doesn't exist, but it's a relative path and any (grand) parent has this file,
# then suggest opening it instead.
function resolve_file() {
  local n="$1"
  if [[ -e "$n" ]] || [[ "$n" =~ ^/ ]]  ; then
    echo "$n"
    return 0
  fi
  {
    echo "[NEW] ./$n"
    for path in $(paths-to-root "$PWD") $(recent-dirs -z -n 30) ; do
      local f="$path$n"
      if [[ -e "$f" ]] ; then
        local rel=$(realpath -s --relative-to="$PWD" "$f")
        if [[ "$rel" =~ ^\.\. ]]; then
          echo $'      \e[48;5;9m'"$path"$'\e[0m'"$n"
        else
          echo "      ./$rel"
        fi
      fi
    done
  } | global-unique | fzf --ansi -1 | ansi-remove| sed -e 's/^[^ ]*  *//'
  return 0
}

for n in "${args[@]}" ; do
  n="$(resolve_file "$n")"
  if [[ "$n" == "" ]] ; then # resolve failed
    exit 1
  fi
  if ! [[ "$n" =~ ^/ ]] ; then
    n="$PWD/$n"
  fi
  if (( $force_editor )) || [[ -d "$n" ]] ; then
    f="$n"
  else
    case "${n##*/}" in
      ravenwood-bugreport*.txt)
        f="$n"
        ;;
#      *bugreport*.zip|*bugreport*.txt|*.br|dumpState_*.log)
#        is_bugreport=1
#        ;;
      *.zip)
#        if is-bugreport "$n" ; then
#          is_bugreport=1
#        else
          f="$(unzip-to-each-dir "$n")"
#        fi
        ;;
      *.tar|*.tar.gz|*.tgz|*.tar.bz2|*.tar.xz|*.7z)
        f="$(unzip-to-each-dir "$n")"
        ;;
      *.deb)
        f=$temp/${n##*/}-$$-list.txt
        ee -2 dpkg -c "$n" > "$f"
        ;;
      *.md|markdown)
        {
          html="$temp/${n##*/}-$$.html"
          pandoc -f gfm -s -V maxwidth="min(95%, 120em)" "$n" -o "$html"
          # Add a styled link to the original Markdown file using the vscode:// protocol.
          sed -i "s|</body>|<div style=\"margin-top: 2em; border-top: 1px dashed #bbb; padding-top: 1em; font-size: 0.85em; opacity: 0.7;\"><a href=\"vscode://file$n\">Open original in VS Code</a></div></body>|i" "$html"
        }
        c "$html"
        continue
        ;;
      *.gif|*.png|*.webp|*.jpeg|*.jpg|*.mp4|*.pdf|*.html|*.htm)
        c "$n"
        continue
        ;;
      *.pdf)
        c "$n"
        continue
        ;;
      *.json)
        if (( $pretty )) ; then
          f=$temp/${n##*/}-$$-pretty.json
          json_pp < "$n" > "$f"
          chmod -w "$f"
        else
          f="$n"
        fi
        ;;
      *.xml)
        if (( $pretty )) ; then
          f=$temp/${n##*/}-$$-pretty.xml
          xml-pretty < "$n" > "$f"
          chmod -w "$f"
        else
          f="$n"
        fi
        ;;
      *.db)
        sqliteman "$n" &
        continue
        ;;
      *.log)
        f="$n"
        force_editor=1
        ;;
      *.jar)
        f="$(jd-jar "$n")"
        ;;
      *.apk)
        f="$(apkext "$n")"
        ;;
      *.gz|*.z)
        f=$temp/${n##*/}-$$-zcat.txt
        ee -2 zcat "$n" > "$f"
        ;;
      *)
        if [[ ! -e "$n" ]] ; then
          f="$n"
        elif [[ -d "$n" ]] || istext "$n"  ; then
          if [[ -f "$n" ]] && istext "$n" && has-ansi "$n" ; then
            c "$n"
            continue
          fi
          f="$n"
        else
          f=$temp/${n##*/}-$$-hexdump.txt
          ee -2 hd "$n" > "$f"
        fi
        ;;
    esac
#    if (( $is_bugreport )) ; then
#      f="$(bugreport-extract -b "$n")"
#      use_vim=1
#    fi
  fi
  files+=("$f")
done

file0="${files[0]}"

if [[ "$EDITOR_ANTIGRAVITY" != "" ]]; then
  if evsniff -a | grep -q 'SHIFT$' ; then
    INFO "Shift key detectd. Force disabling antigravity!" 1>&2
    export EDITOR_ANTIGRAVITY=""
  fi
fi

command=""
is_vi=0
is_code=0
is_antigravity=0
is_gnome_edit=0

candidates=()

if (( $bg != 0 )) ; then
  # Antigravity's "trust folder" check sometimes
  # causes the editor to close right away, even if I chose "trust"...??
  # so let's not use Antigravity.
  candidates+=($EDITOR_ANTIGRAVITY)
fi
candidates+=(/usr/bin/code)

if [[ -n "$DISPLAY" ]] ; then
  if (( $IN_SANDY )) ; then
    command=gnome-text-editor
    is_gnome_edit=1
    bg=0
  elif (( $use_vim )) ; then
    command=gvim
    opts=()
    bg=1
    is_vi=1
  else
    # Update common_Rc to channge EDITOR_ANTIGRAVITY.
    command=$(firstbin "${candidates[@]}")
    if [[ "$command" =~ /code$ ]]; then
      is_code=1
    elif [[ -n "$command" ]] ; then
      is_antigravity=1
    fi
    if ! (( $bg )) ; then
      opts+=("--new-window" "--wait")
    fi
  fi
fi
if [[ -z "$command" ]] ; then
  command=vi
  opts=()
  bg=0
  is_vi=1
fi

if (( $line > 0 )) ; then
  if (( $is_code || $is_antigravity )) ; then
    opts=("-g")
    files[0]="$file0":$line
  elif (( $is_vi )) ; then
    opts=("+$line")
  fi
fi

ee_bg_opt=""
if (( $bg )); then
  ee_bg_opt=-b
fi

if (( $is_code || $is_antigravity )); then
  opts+=( $(chrome-flags-for-vmware) )
  if (( $force_new_window )) || [[ -d "$file0" ]] ; then
    opts+=("-n")
  fi
fi

if (( ${#files[@]} > 0 )) ; then
  if (( $mkpath )) ; then
    for n in "${files[@]}"; do
      dir="$(dirname "$n")"
      if [[ ! -d "$dir" ]] ; then
        ee mkdir -p "$dir"
      fi
    done
  fi

  cd $HOME
  ee $ee_bg_opt $command "${opts[@]}" "${files[@]}" #| zenlog write-to-outer
fi
