#!/bin/bash

# Open a script with 1, without specifying the full path.

. mutil.sh

f="$(which "$1")"
if ! [[ -f "$f" ]] ; then
  if [[ -d "$1" ]] ; then
    ee 1 "$f" # Open a directory instead.
    exit 0
  fi
  echo "$0: '$1' not found." 1>&2
  exit 1
fi

t="$(file -L "$f")"
if ! grep -qPi '(ascii|text)' <<<"$t" ;then
  echo "$0: $f is not a text file.  It's: $t" 1>&2
  exit 1
fi

ee 1 "$f"
