#!/usr/bin/python3

RESET = "\x1b[0m"

def p(value):
    print(value, end="")

def reset():
    p(RESET)

def print_basic_colors(extra=""):
    for bg in range(16):
        for fg in range(16):
            p(f"\x1b[48;5;{bg}m")
            p(f"\x1b[38;5;{fg}m")
            p(extra)
            p(f"{fg:2d}/{bg:2d}")
            reset()
            p(" ")
        p("\n")

p("Reference: https://en.wikipedia.org/wiki/ANSI_escape_code\n")
p("Reference: https://xtermjs.org/docs/api/vtfeatures/\n")
p("Reference: https://gist.github.com/ConnerWill/d4b6c776b509add763e17f9f113fd25b\n")

p("\n")
p("Reset: \\e[0m (or \\x1b[0m)\n")
p("\n")

p("[Normal colors] \\e[38;5;${fg-index}m \\e[48;5;${bg-index}m\n")
print_basic_colors()

p("\n[Bold] \\e[1m\n")
print_basic_colors("\x1b[1m")

p("\n[Faint] \\e[2m\n")
print_basic_colors("\x1b[2m")

# p("\n[Conceal] \\e[8m\n")
# print_basic_colors("\x1b[8m")

p("\n[Gray scale] (index / scale) \\e[38;5;${bg-index}m \\e[38;5;${bg-index}m\n")
for i in range(232, 256):
    p(f"\x1b[38;5;15m")
    p(f"\x1b[48;5;{i}m")
    p(f"{i:3d}")
    reset()
    p(" ")
p("\n")
for i in range(232, 256):
    s = i - 232
    p(f"\x1b[38;5;15m")
    p(f"\x1b[48;5;{i}m")
    p(f"{s:3d}")
    reset()
    p(" ")
p("\n")

p("\n[256 Colors] (index / RGB)  \\e[38;5;${fg-index}m \\e[48;5;${bg-index}m\n")
for r in range(0, 6):
    for mode in [0, 2]:
        for g in range(0, 6):
            for b in range(0, 6):
                c = 16 + (r * 36) + (g * 6) + b
                fg = 15 if g < 3 else 0
                p(f"\x1b[38;5;{fg}m")
                p(f"\x1b[48;5;{c}m")
                if mode == 0:
                    p(f" {c:3d}")
                else:
                    p(f" {r}{g}{b}")
                reset()
            p(" ")
        p("\n")
    p("\n")
p("\n")


p(f"\n\x1b[3;38;5;15m[Italic]{RESET} \\e[3m\n")
p(f"\n\x1b[4;38;5;15m[Underline]{RESET} \\e[4m\n")
p(f"\n\x1b[5;38;5;15m[Slow blink]{RESET} \\e[5m\n")
#p(f"\n\x1b[6;38;5;15m[Rapid blink]{RESET} \\e[6m\n")
p(f"\n\x1b[9;38;5;15m[Crossed-out]{RESET} \\e[9m\n")
p(f"\n\x1b[21;38;5;15m[Doubly-underline]{RESET} \\e[21m\n")

#p(f"\n\x1b[51;38;5;15m[Framed]{RESET} \\e[51m\n")
#p(f"\n\x1b[52;38;5;15m[Encircled]{RESET} \\e[52m\n")
#p(f"\n\x1b[53;38;5;15m[Overlined]{RESET} \\e[53m\n")
