#!/bin/bash

# Shows process names, package names and filenames (and etc) that starts with the token.
{
  adb shell "
      ps -A -w -o NAME             | sed -ne '1d; /^[a-zA-Z0-9]/p' ;
      cmd package list packages    | sed -e 's/^package://' ;
      ls -pd1 '${1:-/}'*
      "
}
