#!/bin/bash

# Used with bind -x as eval "$(bash-move-current-token-file)"
# Take the current token as a filename, let rename it and update
# the command line.
# if -c is passed, it'll copy the file instead

set -e

. mutil.sh

copy=0
if [[ "$1" == -c ]] ; then
    copy=1
fi

# Current token.
from="$(sh-get-current-token -f)"

if [[ -z "$from" ]] ; then
  # No token.
  exit 0
fi

echo "$from" 1>&2

if [[ ! -e "$from" ]]; then
  echo "$from doesn't exist." 1>&2
  exit 1
fi

# Temp file to store the filename.

inst="Renaming $from"
if (( $copy )) ; then
  inst="Copying $from"
fi
to="$(echo "$from" | interactive-edit-line -i "$inst")"

# Error check
if [[ -e "$to" ]]; then
  echo "$to already exists." 1>&2
  exit 1
fi

# Rename or copy
mkdir -p "$(dirname "$to")"
if (( $copy )) ; then
    ee -2 cp "$from" "$to"
else
    ee -2 mv "$from" "$to"
fi

# Update the command line.
sh-replace-current-token -e "$to"
