#!/bin/bash

token="$1"

# Shows process names, package names and filenames (and etc) that starts with the token.

echo "Token='$token'" 1>/tmp/abc

{
  adb shell "
      ps -A -w -o NAME             | sed -ne '1d; /^[a-zA-Z0-9]/p' ;
      cmd package list packages    | sed -e 's/^package://' ;
      ls -pd1 '${token:-/}'*
      "
} | {
  if [[ -z "$token" ]] ; then
    cat
  else
    perl -ne "m!^\Q${token}\E!o and print"
  fi
}
