#!/bin/bash

# Shows process names, package names and filenames (and etc) that starts with the token.

. mutil.sh

android-has-device || exit 0

adbf shell "
    ps -A -w -o pid,name      | sed -e '1d; s/^\(.....\) /{{ \1 }} /; s/^/[DEV-PID] /'
    ps -A -w -o name,pid      | sed -e '1d; s/^\([^ ]*\)/{{ \1 }}/ s/^/[DEV-PROCESS] /'
    cmd package list packages    | sed -e 's/^package:/[DEV-PACKAGE] /' ;
    ls -pd1 '${1:-/}'* | sed -e 's/^/[DEV-FILE] /'
    "
