#!/bin/bash

set -e

. mutil.sh

token="$(sh-get-current-token -f)"

if [[ -n "$token" ]] ; then
    path="$(abspath "$token")"

    if [[ -e "$path" ]] ; then
      sh-replace-current-token "$path"
    fi
fi
