#!/bin/bash

# Used with bind -x as eval "$(bash-move-current-token-file)"
# Take the current token as a filename, let rename it and update
# the command line.

set -e

. mutil.sh

# Current token.
from="$(readline-current-token -f)"

if [[ -z "$from" ]] ; then
  # No token.
  exit 0
fi

if [[ ! -e "$from" ]]; then
  echo "$from doesn't exist." 1>&2
  exit 1
fi

# Temp file to store the filename.
temp=$(tempfile)
trap "rm -f $temp" EXIT

echo "$from" > $temp

# Let the user edit it.
1 -w $temp >/dev/null

# Get the updated name. TODO It doesn't handle spaces properly.
to=$(cat "$temp")

# Has it changed?
if [[ -z "$to" ]] || [[ "$to" = "$from" ]]; then
  exit 0
fi

# Error check
if [[ -e "$to" ]]; then
  echo "$to already exists." 1>&2
  exit 1
fi

# Rename.
mkdir -p "$(dirname "$to")"
mv "$from" "$to"

# Update the command line.
readline-replace -e "$to"
