#!/bin/bash

set -e
. mutil.sh

cd "${MY_BASH_PWDS:?}"

# Find all bash PIDs
pids="$(join-args , $(bash-pids))"

# List their "pwd" files and sort by timestamp (-t), then cat them.
for f in $( ls -t $(eval echo "{$pids}.txt")  2>/dev/null ) ; do
    cat $f
done
