#!/usr/bin/env ruby

require 'optparse'

$debug = false

def debug(*msg)
  $stderr.puts msg if $debug
end

$self_path = File.expand_path(__FILE__)

def do_install(command)
  debug "Installing completion for '#{command}'"

  func = "_#{command}_completion".gsub!(/-/, "-")
  puts <<~EOF
      function #{func} {
        ruby "#{$self_path}" -c "$COMP_CWORD" "${COMP_WORDS[@]}"
        COMPREPLY=('NOT-IMPLEMENTED')
      }
      complete -F #{func} #{command}
      EOF
end

def do_completion()
  word_index = ARGV.shift.to_i
  words = ARGV

  open "/tmp/bc.txt", "w" do |o|
    o.puts <<~EOF
        Index: #{word_index}
        Words: #{words.join ","}
        Current: #{words[word_index]}
        EOF
  end
end

def main()
  OptionParser.new do |opts|
    opts.banner = "Usage: "

    opts.on("-iCOMMAND", "Install completion for COMMAND") do |command|
      do_install command
      exit 0
    end

    opts.on("-c", "Perform completion (shouldn't be used directly)") do
      do_completion
      exit 0
    end

    opts.on("-d", "Enable debug mode") do
      $debug = true
    end
  end.parse!

  $stderr.puts "#{$0}: Invalid arguments."
  exit 1
end

main()
