#!/bin/bash

. ~/cbin/common_rc

. mutil.sh

test=0
if [[ -t 1 ]] ; then
  test=1
fi

if (( $test )) ; then
  export token="$1"
else
  export token="$(sh-get-current-token -f)"
fi

# Filter out uninteresting words
clean() {
  perl -pe '(m!^ (?:
        \( [ \d\/\)\, ]*  # (1/3)
    |   \d+ \%            # 32%

    )$!x) and $_=""'
}

expand() {
  local IFS=$'\n'
  echo "$*"
}

s() {
  sort --ignore-case
}

get_dir() {
  if [[ -d "$token" ]] ; then
    echo "$token"
  else
    echo "$(dirname "$token")"
  fi
}

candidate_files() {
  (
    shopt -s nullglob

    if ! [[ "$token" =~ / ]] ; then
      command ls -A
    else
      local dir="$(get_dir)"
      expand "$dir"/*
    fi
  ) | sort | while read -r n; do
    if [[ -d "$n" ]] ; then
      echo "$n/"
    else
      echo "$n"
    fi
  done
}

maybe_escape() {
  while read -r word ; do
    if [[ "$word" =~ ^\$ ]] ; then
      echo "$word"
    elif [[ "$word" =~ \#verbatim$ ]] ; then
      echo "${word%#verbatim}"
    else
      shescape "$word"
    fi
  done
}

maybe_add_space() {
  while read -r word ; do
    echo -n "$word"
    if [[ -f "$word" ]] ; then
      echo " "
    else
      echo
    fi
  done
}

print() {
  local prefix="$1"
  shift
  timeout 1 perl -pe "print '$prefix'" "$@"
}

cap() {
  local n="$1"
  global-unique | clean | head -n "$n" | s
}

frequent_words() {
  print "[FREQ] " ~/cbin/00-frequent-words.txt
}

git_branches() {
  if in-git ; then
    git branch | s | sed -n '/^..(/d; s/^. //p;' | print "[GIT-BRANCH] "
  fi
}

files() {
  print "[FILES] " <(candidate_files)
}

android_env() {
  if [[ "$ANDROID_BUILD_TOP" == "" ]] ; then
    return
  fi
  print '[ABT] ' <<'EOF'
$ANDROID_BUILD_TOP/build/soong/
$ANDROID_BUILD_TOP/build/make/
$ANDROID_BUILD_TOP/cts/
$ANDROID_BUILD_TOP/frameworks/
$ANDROID_BUILD_TOP/frameworks/base/
$ANDROID_BUILD_TOP/frameworks/base/ravenwood/
$ANDROID_BUILD_TOP/frameworks/base/ravenwood/scripts/
$ANDROID_BUILD_TOP/frameworks/base/ravenwood/scripts/run-ravenwood-tests.sh -s
$ANDROID_BUILD_TOP/frameworks/base/ravenwood/tools/hoststubgen/
$ANDROID_BUILD_TOP/frameworks/base/ravenwood/tools/hoststubgen/test-tiny-framework
$ANDROID_BUILD_TOP/out/
$ANDROID_BUILD_TOP/out/soong/.intermediates/
$ANDROID_BUILD_TOP/out/soong/.intermediates/frameworks/
$ANDROID_BUILD_TOP/out/soong/.intermediates/frameworks/base/
$ANDROID_BUILD_TOP/out/soong/.intermediates/frameworks/base/ravenwood
$ANDROID_HOST_OUT/
$ANDROID_HOST_OUT/testcases/
$ANDROID_HOST_OUT/testcases/ravenwood-runtime/
EOF
}

envs() {
  print '[ENV] $' <(
    env | sed -e 's/=.*//' | s
  )
}

recent_dirs() {
  print "[RECENT-DIR] " <(
    timeout 0.5 recent-dirs -n 50 -z | cap 50
  )
}

# recent_urls() {
#   print "[$2] " <(
#     timeout 0.1 zenlog-last-n-contents -R -n $1 | perl -ne '
#       while (m! ( (?: file | https? ) \:\/\/ [^ \) ] + ) !xg) {
#         print $1, "\n"
#       }
#     ' | cap 100
#   )
# }

recent_files() {
  print "[$2] " <(
    timeout 0.3 zenlog-recent-files -d -n $1 | cap 1000 | dir-slash
  )
}

recent_words() {
  print "[$2] " <(
    timeout 0.3 zenlog-last-n-contents -R -n $1 | zenlog-recent-words.pl | cap 20000
  )
}


bfs_inner() {
  {
    local timeout=0.2
    local opts="-nocolor -maxdepth 6 -name .git -prune -o -name e2etests -prune -o -name .cache -prune -o -print "
    if ! [[ "$token" =~ / ]] ; then
      timeout $timeout bfs $opts | sed -e 's!^\./!!'
    else
      local dir="$(get_dir)"
      timeout $timeout bfs $opts "$dir"
    fi
  } 2>/dev/null
}

bfs() {
  print '[BFS] ' <(
    bfs_inner | cap 10000
  )
}

soong_modules_inner() {
  local mod="$OUT/module-info.json"
  local cache="$OUT/module-info-modules.cache.tmp"
  local tmp="$OUT/module-info.tmp"

  if ! [[ -f "$mod" ]] ; then
    return 0
  fi

  if [[ "$mod" -nt "$cache" ]] ; then
    rm -f "$cache" "$tmp"
    {
      jq -r 'to_entries[] | .key' "$mod" | s > "$tmp"
    } && mv "$tmp" "$cache"
  fi
  cat "$cache"
}

soong_modules() {
  print '[MODULES] ' <(
    soong_modules_inner
  )
}

filter() {
  while read -r prefix line ; do
    if [[ -d "$line" ]] ; then
      #if ! [[ "$line" =~ /$ ]]; then
      #  line="$line/"
      #fi
      echo "${prefix} "$'\e[38;5;10m'"${line}"$'\e[0m'
    
    elif [[ -e "$line" ]] ; then
      echo "${prefix} "$'\e[38;5;14m'"${line}"$'\e[0m'
    
    elif [[ "$prefix" == "[ENV]" ]] ; then
      echo "${prefix} "$'\e[38;5;13m'"${line}"$'\e[0m'
    else
      echo "${prefix} ${line}"
    fi
  done
}

# export FZF_DEFAULT_OPTS="--color=bg+:4,header:2 --no-mouse --no-sort --algo=v1 -e"\
# " --bind='ctrl-y:abort,"\
# "home:execute(wait-for-key),"\
# "ctrl-g:ignore,"\
# "alt-1:execute-silent(fzf-1 {+}),"\
# "alt-o:execute-silent(fzf-o {+}),"\
# "alt-i:execute-silent(fzf-io {+}),"\
# "alt-c:execute-silent(fzf-copy-args {+}),"\
# "alt-m:execute-silent(imv {+}),"\
# "ctrl-f:preview-page-down,ctrl-r:preview-page-up,ctrl-b:preview-page-up,"\
# "ctrl-k:kill-line'"\
# " --preview-window=top"\
# " --header 'Home: flip screen  Alt+1: open with 1  Alt+o: open with o Atl+i: open with ij  Alt+c: copy  Alt+m: imv  Ctrl+f/r: preview scroll'"

# need to replace {+} to {+2..}

export FZF_DEFAULT_OPTS="$(perl -pe 's!\{.*?\}!{+2..}!g' <<<"$FZF_DEFAULT_OPTS")"

completed=$({
    cat \
      <(git_branches) \
      <(recent_files 2 LAST-FILES) \
      <(recent_words 2 LAST-WORDS) \
      <(files) \
      <(android_env) \
      <(envs) \
      <(recent_dirs) \
      <(frequent_words) \
      <(recent_files 5 RECENT-FILES) \
      <(recent_words 5 RECENT-WORDS) \
      <(bfs) \
      <(soong_modules)
  } | filter |
    fzf --ansi -1 -q "$token" -m --preview='preview-file {2..}' |
      perl -pe 's!^\S+\s*!!;' |
      maybe_escape |
      maybe_add_space |
      add-backslash-except-for-last
)

if [[ -n "$completed" ]] ; then
  if (( $test )) ; then
    echo "'$completed'"
  else
    sh-replace-current-token "$completed"
  fi
fi
