#!/usr/bin/env ruby

require 'optparse'

$self_path = File.expand_path(__FILE__)
$debug = false

def debug(*msg, &b)
  if $debug
    $stderr.puts msg
    b.call if b
    return 1
  else
    return 0
  end
end

def do_install(command, script)
  debug "Installing completion for '#{command}'"

  func = "_#{command}_completion".gsub!(/-/, "-")
  debug_flag = debug ? "-d" : ""
  puts <<~EOF
      function #{func} {
        IFS='
'
        COMPREPLY=( $(ruby "#{$self_path}" #{debug_flag} -c "$COMP_CWORD" "${COMP_WORDS[@]}" <<'SCRIPT_END'
#{script}
SCRIPT_END
) )
      }
      complete -F #{func} #{command}
      EOF
end

def do_completion()
  word_index = ARGV.shift.to_i
  words = ARGV

  debug do
    open "/tmp/bc.txt", "w" do |o|
      o.puts <<~EOF
          Index: #{word_index}
          Words: #{words.join ","}
          Current: #{words[word_index]}
          EOF
    end
  end
end

def main()
  OptionParser.new do |opts|
    opts.banner = "Usage: "

    opts.on("-iCOMMAND", "Install completion for COMMAND") do |command|
      script = $stdin.read
      do_install command, script
      exit 0
    end

    opts.on("-c", "Perform completion (shouldn't be used directly)") do
      do_completion
      exit 0
    end

    opts.on("-d", "Enable debug mode") do
      $debug = true
    end
  end.parse!

  $stderr.puts "#{$0}: Invalid arguments."
  exit 1
end

main()
