#!/bin/bash

# sudo apt-get install acpi

ACPI=/usr/bin/acpi
MIN_PERCENT=${1:-20}

if ! which $ACPI >&/dev/null ; then
    echo "acpi not installed."
    exit 10
fi

acpi="$( $ACPI 2>&1)"

if egrep -q ' (power_supply|Full)' <<<"$acpi" ; then
    exit 0
fi

if ! grep -q ' Charging' <<<"$acpi" ; then
    echo "Battery discharging."
    exit 11
fi

percent="$(perl -ne  '/(\d+)%/ and print $1' <<<"$acpi")"
percent=${percent:-0}

echo "Battery level is: $percent"
if (( $percent < "$MIN_PERCENT" )) ; then
    echo "Battery level too low. ($percent < $MIN_PERCENT)"
    exit 12
fi

exit 0
