#!/bin/bash

export PATH="$PATH:$HOME/cbin:$HOME/cbin/misc"

set -e
. mutil.sh

delay=0
copy_image=0
eval "$(bashgetopt '
d|delay          delay=3          # Delay 3 seconds
i|copy-image     copy_image=1     # Copy the image to the clipboard
' "$@")"

label=""

if (( $# > 0 )) ; then
  label="_$(perl -pe 'chomp; s!\s+!_!g' <<< "$*")"
fi

out=$HOME/Downloads/screenshot-$(date8)${label}.png

sleep $delay

echo "Select a region and press CTRL+C to capture:"

import "$out" # Using imagemagick # With imagemagic

if (( $copy_image )) ; then
  xclip -selection clipboard -t image/png -i $out
  notify-send -t 3 "Screenshot captured into clipboard"
else
  echo "$out" | xclip -r -selection clipboard -t text/plain
  INFO 'Captured into:' $out
  ee -qb ksnip -e $out
fi