#!/bin/bash

set -e
. mutil.sh

verbose=0

eval "$(bashgetopt '
v|verbose          verbose=1       # Make verbose
' "$@")"

fingerprint_file="cbin-fingerprint.dat"
fingerprint_local="$HOME/cbin/misc/$fingerprint_file"
fingerprint_remote="https://raw.githubusercontent.com/omakoto/misc/refs/heads/master/$fingerprint_file"

subcommand="$1"

status() {
    local ee=""
    if (( $verbose )) ; then
        ee="ee -2"
    fi
    local remote="$($ee curl -s "${fingerprint_remote}?$RANDOM")"
    local loc="$(cat $fingerprint_local)"
    if (( $verbose )); then
        INFO "Remote:" "$remote"
        INFO "Local: " "$loc"
    fi
    if [[ "$remote" == "$(cat $fingerprint_local)" ]]; then
        INFO "cbin is up-to-date"
    else
        # bmagenta "*** cbin needs pulling ***"
        notify -t "cbin checker" "*** cbin needs pulling ***"
    fi
}

update() {
    if ! cbin-is-uptodate ; then
        INFO "Change detected. Updating $fingerprint_file"
        date > $fingerprint_file
    fi
    return 0
}

case "$subcommand" in
status|"") status ;;
update) update ;;
*)
    echo "Unknown subcommand: $subcommand" 1>&2
    exit 1
    ;;
esac
