#!/bin/bash
# Simple script, no help needed.
# Prints '--disable-gpu' if running under VMware.

if [[ "$IS_VMWARE" == "1" ]] || { [[ -f /sys/class/dmi/id/product_name ]] && grep -qi "^vmware" /sys/class/dmi/id/product_name 2>/dev/null; }; then
  echo "--disable-gpu"
fi
