#!/bin/bash

# Smart "open with chrome".

set -e

. mutil.sh

app=0
profdir=""

eval "$(bashgetopt -d 'Run Chrome' '
p|profile=s  profdir=$HOME/.chrome-profiles/%s           # specify profile directory name
a|app        app=1                                       # start as app
' "$@")"

# Parse the argument.

url="$1"

function temphtml() {
    tempfile --suffix=.html
}


# If there's no argument, and STDIN is not terminal, #'
# read from stdin.
if [[ -z "$url" ]] && ! [[ -t 0 ]] ; then
  url=$( temphtml )
  cat > "$url"
  if ! [[ -s "$url" ]] ; then
    # File empty.
    rm -f "$url"
    url=""
  fi
fi

if [[ -f "$url" ]]; then
  case "$url" in
  *.gif|*.png|*.webp|*.jpeg|*.jpg|*.mp4|*.pdf) ;;
  *)
    if ! isbin "$url" && has-ansi "$url" ; then
      url2=$( temphtml )
      head="$(head -1 "$url" 2>/dev/null | ansi-remove | sed -e 's/^\$ *//')"
      a2h -font-size 8pt -title "$head [a2h]" < "$url" > "$url2"
      url="$url2"
    fi
    ;;
  esac
fi

# build the parameters.

params=()

if [[ -n "$profdir" ]]; then
  params+=("--user-data-dir=$profdir")
  echo "profile=$profdir"
  if ! [[ -d "$profdir/" ]] ; then
    mkdir -p "$profdir"
  fi
fi

# This file is written by pc-config-update
dpi=$(cat ~/.chromedpi 2>/dev/null || true)

if [[ -n "$dpi" ]] ; then
  params+=("--force-device-scale-factor=$dpi")
fi

if (( $app )) ; then
  params+=("--app=$url")
else
  params+=("$url")
fi

echo "( google-chrome "${params[@]}" &) >/dev/null 2>&1"
