#!/bin/bash

value="''"

if (( "${1:-1}" != 0 )) ; then
    value="'<Alt>'"
fi

ee dconf write /org/gnome/desktop/wm/preferences/mouse-button-modifier "$value"
ee dconf write /org/cinnamon/desktop/wm/preferences/mouse-button-modifier "$value"
