#!/bin/bash
# Bash completion tester.
# Install it with . <(comptest --install)

set -e
. mutil.sh

# If the first argument is "--install", then print the install script.
if [[ "$1" == "--install" ]] ; then
  this="${BASH_SOURCE[0]}"
  cat <<EOF
function __comptest_completion() {
  . <(sed -ne '/^#__COMPLETION_SCRIPT__/,\$p' '$this')
}

complete -F __comptest_completion comptest
EOF
  exit 0
fi

# Otherwise, just print all arguments.
echo "\$@="$(shescape "$@")

exit 0

#__COMPLETION_SCRIPT__
local IFS
{
  for n in \
      COMP_CWORD \
      COMP_KEY \
      COMP_LINE \
      COMP_POINT \
      COMP_TYPE \
      COMP_WORDBREAKS \
      COMP_WORDS \
      ; do
    declare -p "$n"
  done
  echo "Self extracted words"
  sh-split-words -ai -- "$COMP_LINE"
} >/tmp/compin.txt 2>/dev/null
touch /tmp/compreply.txt
EE_QUIET=1 1 /tmp/compin.txt
EE_QUIET=1 1 /tmp/compreply.txt
IFS=$'\n'
COMPTYPE=33
COMPREPLY=($(sed -n -e '/^[^#]/p' /tmp/compreply.txt 2>/dev/null))
sed -n -e 's/^#//p' /tmp/compreply.txt 1>&2
# COMPREPLY=($(ls $HOME | fzf))

# declare -- COMP_TYPE="33" -- first call
# declare -- COMP_TYPE="63" -- second call
