#!/bin/bash

selected=$(select-menu \
'C: Copy last zenlog output w/o command' \
'F: Copy last zenlog output w/ command' \
'L: Copy current command line' \
'D: Copy current dir' \
)

case "$selected" in
    C)
        zenlog-last-n-contents -n 1 -t -c
        ;;
    F)
        zenlog-last-n-contents -n 1 -c
        ;;
    L)
        echo "$READLINE_LINE" | cb -D '[Copied current commandline to clipboard]'
        ;;
    D)
        echo "$PWD" | cb -D '[Copied current dir to clipboard]'
        ;;
    *)
        exit 1
esac
