#!/bin/bash

commands=\
'1: Copy last zenlog output w/o command
2: Copy last zenlog output w/ command
3: Copy current command line'

selected=$(
    {
        cat <<<"$commands"
    } | fzf -1
)

case "$selected" in
    1*)
        zenlog-last-n-contents -n 1 -t -c
        ;;
    2*)
        zenlog-last-n-contents -n 1 -c
        ;;
    3*)
        echo "$READLINE_LINE" | cb -D '[Copied current commandline to clipboard]'
        ;;
    *)
        exit 1
esac
