#!/bin/bash

selected=$(select-menu \
'1: Copy last zenlog output w/o command' \
'2: Copy last zenlog output w/ command' \
'3: Copy current command line' \
'4: Copy current dir' \
)

case "$selected" in
    1)
        zenlog-last-n-contents -n 1 -t -c
        ;;
    2)
        zenlog-last-n-contents -n 1 -c
        ;;
    3)
        echo "$READLINE_LINE" | cb -D '[Copied current commandline to clipboard]'
        ;;
    4)
        echo "$PWD" | cb -D '[Copied current dir to clipboard]'
        ;;
    *)
        exit 1
esac
