#!/bin/bash

set -e
. mutil.sh

taskname="${1?First argument must be task name}"
ndays="${2:-1}"

checkfile=/tmp/task-timestamp-$taskname

if [[ -f "$checkfile" ]] ; then
    if (( $(fileage "$checkfile") < $ndays )) ; then
        INFO "Skipping task:" "$taskname"
        exit 1
    fi
fi

INFO "Running task:" "$taskname"
touch "$checkfile"
exit 0

