#!/bin/bash

# Shorten/normalize directory names.
# Delegated to the dir-normalize() shell function.
# Run test: cd ~/cbin/misc && ./dir-normalize_test.bash

declare -f dir-normalize > /dev/null || . mutil.sh

dir-normalize "$@"
