#!/usr/bin/perl -w

use strict;
use lib ($0 =~ s!/[^/]+$!!r); #!
use MCommon;
use IsFile;

$| = 1;

while (defined(my $l = <>)) {
  chomp $l;
  if (-f $l or -d $l) {
    print $l, "\n";
    next
  }
  while ($l =~ m! (( [$ENV{FILE_RE_CHARS}]+ ) (?: \:\d+ (?: \:\d+ )? )? ) !gox) {
    print STDERR "$1 : $2\n";
    my $file = $2;
    my $file_with_line = $1;
    next if $file =~ m!^( \. | \/+ )$!x;
    if (isfile($file)) {
      print $file_with_line, "\n";
    }
  }
}
