#!/bin/bash

. mutil.sh

out=${TEMP:-/tmp}/$$.tmp
echo "Work file: $out"

strace -f -X verbose -e 'open,creat,openat' -o$out "$@"
rc=$?

echo "Files acceesed:"
perl -ne 'while (m!"(.*?)"!g) { print "$1\n";} ' $out | sort -u

exit $rc
