#!/bin/bash

SCRIPT="${0##*/}"
SCRIPT_DIR="${0%/*}"

PATH="$SCRIPT_DIR:/bin:/sbin:$PATH"

success_file=/tmp/fstrim-last-success.log
log=/tmp/fstrim-"$(date '+%Y%m%d-%H%M%S')-$$".log

min_interval_minues=$(( 1 * 24 * 60 ))
# min_interval_minues=$(( 1 ))

function run() {
    echo "Log file: $log"
    echo "Checking if we should/can start trimming $@ ..."
    cd "$SCRIPT_DIR" || return 1

    if [[ -f "$success_file" ]] &&
        (( $(file_age_m "$success_file" ) < $min_interval_minues )) ; then
      echo "Last trim time too new; skipping."
      exit 10
    fi

    battery_ok || return 2
    is_idle || return 3

    for disk in "$@"; do
        echo "Trimming $disk ..."
        fstrim -v "$disk"
    done
}

run "$@" |& tee $log
rc=${PIPESTATUS[0]}

if (( $rc == 0 )) ; then
  ln -fs $log $success_file
fi

exit $rc
