#!/bin/bash

# Select lines, 

set -e

# Select the line
line="$( zenlog-last-n-contents -n 10 | tac | fzf -m )"

tokenize() {
    local line="$1"
    {
        # Each token
        echo "$line" | tr -s ' ' '\n' 

        # Special case: "Running: "...
        echo "$line" | sed -ne 's!^Running: !!p'

        # Whole line
        echo "$line"
    } | grep -v '^$' | fzf -1 -m --tac | tr -s '\n' ' '
}


echo "$( tokenize "$line" ) "
