#!/bin/bash

# Select lines, 

set -e
. mutil.sh

# Select the line
line="$( 
    zenlog-last-n-contents -r -n 20 |
    cr-lines-remove |
    tac |
    fzf -m --ansi |
    perl -pe 's/^\s+//'
)"

if [[ "$line" == "" ]] ; then
    exit 1
fi

bar="$(gray -f -- '--------')"
export bar

col() {
    local c=$1
    awk '{ print $'$c'}'
}

tokenize() {
    local line="$1"

    # Remove unnecessary line start tokens
    line="$( perl -pe '
#line 33

s!^Running: !!; # EE marker

s!^ \$\s+ !!x; # Prompt 

' <<<"$line" )"

    {
        # Show vertical lines
        if (( "$(wc -l <<<"$line")" > 1 )); then
            for i in $(seq 1 9); do
                echo -n "$(col $i <<< "$line")"
                echo -n ' '
                echo
                echo $bar
            done
        fi

        split="$( perl -ne '
#line 39

chomp;

# Remove "obvious" line start tokens
s!^ ([a-zA-Z]|\?\?) \s+ !!x; #git markers

# Split by space and print in each line
if ($a = s!\s+!\n!gr) {
    print $a, "\n";
    print $ENV{bar}, "\n";
}

' <<<"$line" )"
        if [[ "$split" != "" ]] && [[ "$line" != "$split" ]] ; then
            echo "$split"
        fi

        # Whole line(s)
        echo "$line"
    } | uniq | grep -v '^$' | fzf --ansi -1 -m --tac | tr -s '\n' ' '
}


echo "$( tokenize "$line" )"
