#!/bin/bash

set -e

# When run inside Antigravity/Claude, it launches in a new gnome-terminal using run-in-terminal.
. "$(dirname "$(readlink -f "$0")")/relaunch-in-terminal.sh" --geometry=160x45 --command=run-in-terminal -- git-commit-history "$@"

list-files -r -n 1000 "${GIT_COMMIT_HISTORY_DIR:?}" | xargs cat | {
    if [[ -t 1 ]] ; then
        hl '^    .*' '@cyan' \
        '^[^ ].*' '@yellow' \
        '\+(?=[+\-]*\s*$)' '@green' \
        '\-(?=[+\-]*\s*$)' '@red' |
        less --raw
    else
        cat
    fi
}

