#!/bin/bash
# Shortcut script to execute git-meld-history.

# When run inside Antigravity/Claude, it launches in a new gnome-terminal.
script_dir=$(dirname "$(readlink -f "$0")")
if "$script_dir/is-in-agent"; then
  exec env -u ANTIGRAVITY_AGENT -u CLAUDE_AGENT gnome-terminal -- gg "$@"
fi

exec git meld-history "$@"
