#!/bin/bash

set -e

# When run inside Antigravity/Claude, it launches in a new gnome-terminal using run-in-terminal.
if needs-term; then
  exec term --geometry=160x45 --no-wait -- "$0" "$@"
fi

git-commit-history-raw | {
    if [[ -t 1 ]] ; then
        hl '^    .*' '@cyan' \
        '^[^ ].*' '@yellow' \
        '\+(?=[+\-]*\s*$)' '@green' \
        '\-(?=[+\-]*\s*$)' '@red' |
        less --raw
    else
        cat
    fi
}

