#!/bin/bash

quiet=0
check_upstream=1
verbose=0
while getopts "qUv" opt; do
    case "$opt" in
    q) quiet=1 ;;
    U) check_upstream=0 ;;
    v) verbose=1 ;;
    *) exit 1 ;;
    esac
done
shift $(($OPTIND - 1))

if (( $quiet )) ; then
    exec 2>/dev/null
fi

check() {
    local dir="$1"
    cd "$dir"
    if ! git rev-parse --is-inside-work-tree >&/dev/null ; then
        echo "$dir is not in a git tree" 1>&2
        return 3
    fi
    if [[ -n "$(git status --porcelain 2>&1)" ]] ; then
        echo "$dir contains uncommit files" 1>&2
        return 2
    fi

    if (( $check_upstream )) ; then
        upstream="$(git upstream)"

        if ! git diff --quiet "$upstream"...HEAD; then
            echo "$dir contains local changes" 1>&2
            return 1
        fi
    fi
    if (( $verbose )) ; then
        echo "$dir is clean" 1>&2
    fi
}

check "${1:-$PWD}"

