#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Interactive Git history viewer using fzf and git-meld (Python implementation).
# See git-meld-history.md for details on specifications.

import sys
import os
import subprocess
import time
import tempfile
import shlex
from typing import List, Optional, Any

# Ensure we quote properly when printing executed commands
def run_command(
    cmd: List[str],
    check: bool = False,
    capture_output: bool = False,
    text: bool = False,
    env: Optional[dict[str, str]] = None
) -> subprocess.CompletedProcess[Any]:
    sys.stderr.write(f"+ {shlex.join(cmd)}\n")
    sys.stderr.flush()
    return subprocess.run(cmd, check=check, capture_output=capture_output, text=text, env=env)

def print_help() -> None:
    sys.stdout.write("""git-meld-history - Interactive Git history viewer using fzf and git-meld.

Usage:
  git-meld-history [<directory>] [<git-log-options>...]

If <directory> is specified, the script runs in that directory. If it is
not a top-level git repository directory, the history is limited to that
directory, but diffs will show all changed files in the commits.

Options:
  -h, --help           Show this help message and exit.
  --bash-completion    Print bash completion script.

Examples:
  # Open history viewer for the current repository:
  git-meld-history

  # Open history viewer for a specific directory:
  git-meld-history src/components

  # Limit history to commits by a specific author:
  git-meld-history . --author="John Doe"
""")
    sys.stdout.flush()

def print_completion() -> None:
    sys.stdout.write("""# Bash autocomplete script for git-meld-history.
# Generated by git-meld-history --bash-completion.

_git_meld_history() {
  local cur prev words cword
  if declare -F _get_comp_words_by_ref >/dev/null 2>&1; then
    _get_comp_words_by_ref -n =: cur prev words cword
  else
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD
  fi

  local start_idx=1
  if [[ "${words[0]}" == "git" ]]; then
    start_idx=2
  fi

  if (( cword == start_idx )); then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help --bash-completion" -- "$cur") )
      return 0
    fi
    COMPREPLY=( $(compgen -d -- "$cur") )
    return 0
  fi

  local dir="${words[start_idx]}"
  local pushed=0
  if [[ -d "$dir" ]]; then
    pushed=1
    pushd "$dir" >/dev/null
  fi

  local new_words=()
  local new_cword
  
  if [[ "${words[0]}" == "git" ]]; then
    new_words=("git" "log" "${words[@]:3}")
    new_cword=$((cword - 1))
  else
    new_words=("git" "log" "${words[@]:2}")
    new_cword=$cword
  fi

  local orig_words=("${COMP_WORDS[@]}")
  local orig_cword=$COMP_CWORD

  COMP_WORDS=("${new_words[@]}")
  COMP_CWORD=$new_cword
  
  if declare -F _git_log >/dev/null 2>&1; then
    _git_log
  else
    COMPREPLY=( $(compgen -f -- "$cur") )
  fi
  
  COMP_WORDS=("${orig_words[@]}")
  COMP_CWORD=$orig_cword

  if (( pushed )); then
    popd >/dev/null
  fi
}

complete -o filenames -o bashdefault -F _git_meld_history git-meld-history git-meld-history.py
""")
    sys.stdout.flush()

def is_inside_work_tree() -> bool:
    res = run_command(["git", "rev-parse", "--is-inside-work-tree"], capture_output=True)
    return res.returncode == 0

def run_sequence_editor(todo_file: str) -> None:
    squash_hashes_str = os.environ.get("SQUASH_HASHES", "")
    squash_hashes = set(squash_hashes_str.split())
    
    if not squash_hashes:
        return

    with open(todo_file, "r") as f:
        lines = f.readlines()

    new_lines = []
    squash_lines = []
    anchor_seen = False
    
    for line in lines:
        parts = line.strip().split()
        if len(parts) >= 2 and not line.startswith("#"):
            cmd = parts[0]
            sha = parts[1]
            try:
                full_sha = subprocess.check_output(
                    ["git", "rev-parse", "--verify", sha],
                    stderr=subprocess.DEVNULL,
                    text=True
                ).strip()
            except subprocess.CalledProcessError:
                full_sha = ""
                
            if full_sha in squash_hashes:
                if not anchor_seen:
                    anchor_seen = True
                else:
                    rest = line.strip()[len(cmd) + len(sha) + 1:].strip()
                    squash_lines.append(f"squash {sha} {rest}\n")

    anchor_seen = False
    for line in lines:
        parts = line.strip().split()
        if len(parts) >= 2 and not line.startswith("#"):
            sha = parts[1]
            try:
                full_sha = subprocess.check_output(
                    ["git", "rev-parse", "--verify", sha],
                    stderr=subprocess.DEVNULL,
                    text=True
                ).strip()
            except subprocess.CalledProcessError:
                full_sha = ""
                
            if full_sha in squash_hashes:
                if not anchor_seen:
                    anchor_seen = True
                    new_lines.append(line)
                    new_lines.extend(squash_lines)
                else:
                    pass
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)

    with open(todo_file, "w") as f:
        f.writelines(new_lines)

def main() -> None:
    os.environ["GIT_OPTIONAL_LOCKS"] = "0"
    args: List[str] = sys.argv[1:]

    if args and args[0] == "--sequence-editor":
        if len(args) < 2:
            sys.stderr.write("Error: Missing todo file path for --sequence-editor\n")
            sys.exit(1)
        run_sequence_editor(args[1])
        sys.exit(0)
    
    if args and args[0] in ("-h", "--help"):
        print_help()
        sys.exit(0)
        
    if args and args[0] == "--bash-completion":
        print_completion()
        sys.exit(0)
        
    # If no arguments are provided, start from the git top-level directory
    if not args:
        toplevel_res = run_command(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True)
        if toplevel_res.returncode == 0:
            toplevel = toplevel_res.stdout.strip()
            if toplevel:
                try:
                    os.chdir(toplevel)
                except Exception as e:
                    sys.stderr.write(f"Error: Could not change directory to {toplevel}: {e}\n")
                    sys.exit(1)
                    
    # If the first argument is specified, assume it's a directory and change to it
    if args and args[0] != "":
        target_dir = args[0]
        try:
            os.chdir(target_dir)
        except Exception as e:
            sys.stderr.write(f"Error: Could not change directory to {target_dir}: {e}\n")
            sys.exit(1)
        args = args[1:]
        
    # Ensure we are inside a git repository
    if not is_inside_work_tree():
        sys.stderr.write("Error: Not a git repository\n")
        sys.exit(1)
        
    toplevel_res = run_command(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True)
    toplevel = toplevel_res.stdout.strip() if toplevel_res.returncode == 0 else ""
    current_dir = os.path.realpath(os.getcwd())
    
    extra_args: List[str] = []
    if toplevel and os.path.realpath(toplevel) != current_dir:
        extra_args.append(".")
        
    while True:
        # Check if dirty
        status_res = run_command(["git", "status", "--porcelain"], capture_output=True, text=True)
        is_dirty = bool(status_res.stdout.strip())
        
        if is_dirty:
            header = "[ESC]: Quit, Single-item [Enter]: Show diff, Two-item [Enter]: Diff between commits (inclusive), Multi-select [^S]: Squash commits, [^I]: Inject"
            fzf_cmd = ["git-history-fzf", "-c", "--submodules", "-e", "ctrl-s,ctrl-i", "-h", header] + args + extra_args
        else:
            header = "[ESC]: Quit, Single-item [Enter]: Show diff, Two-item [Enter]: Diff between commits (inclusive), Multi-select [^S]: Squash commits"
            fzf_cmd = ["git-history-fzf", "-c", "--submodules", "-e", "ctrl-s", "-h", header] + args + extra_args
            
        fzf_res = run_command(fzf_cmd, capture_output=True, text=True)
        fzf_output = fzf_res.stdout
        
        if not fzf_output:
            break
            
        lines = fzf_output.splitlines()
        if not lines:
            break
            
        key = lines[0]
        selections = lines[1:]
        
        if key == "ctrl-i":
            if is_dirty:
                res_inject = run_command(["git-rebase-inject"] + args)
                sys.exit(res_inject.returncode)
            else:
                sys.stderr.write("Error: Inject is only available when the worktree is dirty.\n")
                sys.stderr.flush()
                time.sleep(2)
                continue
                
        if not selections:
            break
            
        submodule_dir = ""
        for line in selections:
            if line.startswith("(submodule) "):
                submodule_dir = line[len("(submodule) "):]
                break
                
        if submodule_dir:
            if submodule_dir == "(Parent)":
                parent_res = run_command(["git", "rev-parse", "--show-superproject-working-tree"], capture_output=True, text=True)
                parent_dir = parent_res.stdout.strip() if parent_res.returncode == 0 else ""
                if parent_dir:
                    submodule_dir = parent_dir
                else:
                    sys.stderr.write("Error: Not inside a submodule\n")
                    sys.stderr.flush()
                    time.sleep(2)
                    continue
            try:
                os.chdir(submodule_dir)
            except Exception as e:
                sys.stderr.write(f"Error: Could not change directory to {submodule_dir}: {e}\n")
                sys.stderr.flush()
                time.sleep(2)
            continue
            
        hashes: List[str] = []
        has_current = False
        for line in selections:
            if line.strip():
                parts = line.split()
                if parts:
                    h = parts[0]
                    if "(CURRENT)" in h:
                        has_current = True
                        hashes.append("(CURRENT)")
                    else:
                        hashes.append(h)
                        
        num_hashes = len(hashes)
        if num_hashes == 0:
            break
            
        if key == "ctrl-s":
            if has_current:
                sys.stderr.write("Error: Cannot squash local changes (CURRENT)\n")
                sys.stderr.flush()
                time.sleep(2)
                continue
            if num_hashes < 2:
                sys.stderr.write("Error: Please select at least 2 commits to squash\n")
                sys.stderr.flush()
                time.sleep(2)
                continue
                
            full_selected_hashes: List[str] = []
            for h in hashes:
                verify_res = run_command(["git", "rev-parse", "--verify", h], capture_output=True, text=True)
                full_selected_hashes.append(verify_res.stdout.strip())
                
            sort_res = run_command(
                ["git", "log", "--no-walk", "--date-order", "--reverse", "--format=%H"] + full_selected_hashes,
                capture_output=True, text=True
            )
            sorted_hashes = sort_res.stdout.splitlines()
            if not sorted_hashes:
                continue
            oldest = sorted_hashes[0]
            
            parent_verify = run_command(["git", "rev-parse", "--verify", f"{oldest}^"], capture_output=True)
            if parent_verify.returncode == 0:
                rebase_base = f"{oldest}^"
            else:
                rebase_base = "--root"
                
            editor_script = os.path.abspath(sys.argv[0])
            env = os.environ.copy()
            env["SQUASH_HASHES"] = " ".join(sorted_hashes)
            env["GIT_SEQUENCE_EDITOR"] = f"{sys.executable} {shlex.quote(editor_script)} --sequence-editor"
            
            if rebase_base == "--root":
                rebase_cmd = ["git", "rebase", "-i", "--root"]
            else:
                rebase_cmd = ["git", "rebase", "-i", rebase_base]
                
            res_rebase = run_command(rebase_cmd, env=env)
            rebase_status = res_rebase.returncode
                    
            if rebase_status != 0:
                sys.stderr.write("Rebase/squash failed or paused for conflict resolution.\n")
                sys.stderr.write("Exiting script so you can resolve it in your terminal (using git rebase --continue/--abort).\n")
                sys.stderr.flush()
                break
            continue
            
        if num_hashes == 1:
            commit = hashes[0]
            if commit == "(CURRENT)":
                res_untracked = run_command(["git", "ls-files", "-z", "--others", "--exclude-standard"], capture_output=True)
                untracked_files = [f.decode('utf-8') for f in res_untracked.stdout.split(b"\x00") if f]
                
                if untracked_files:
                    run_command(["git", "add", "-N", "--"] + untracked_files)
                    
                run_command(["git", "meld", "HEAD"])
                
                if untracked_files:
                    run_command(["git", "reset", "HEAD", "--"] + untracked_files)
            else:
                parent_verify = run_command(["git", "rev-parse", "--verify", f"{commit}^"], capture_output=True)
                if parent_verify.returncode == 0:
                    run_command(["git", "meld", f"{commit}^..{commit}"])
                else:
                    run_command(["git", "meld", f"4b825dc642cb6eb9a001e5408d69288fbee4904f..{commit}"])
        else:
            if has_current:
                historical_hashes = [h for h in hashes if h != "(CURRENT)"]
                sort_res = run_command(
                    ["git", "log", "--no-walk", "--date-order", "--reverse", "--format=%H"] + historical_hashes,
                    capture_output=True, text=True
                )
                sorted_hashes = sort_res.stdout.splitlines()
                if sorted_hashes:
                    oldest = sorted_hashes[0]
                    res_untracked = run_command(["git", "ls-files", "-z", "--others", "--exclude-standard"], capture_output=True)
                    untracked_files = [f.decode('utf-8') for f in res_untracked.stdout.split(b"\x00") if f]
                    
                    if untracked_files:
                        run_command(["git", "add", "-N", "--"] + untracked_files)
                        
                    parent_verify = run_command(["git", "rev-parse", "--verify", f"{oldest}^"], capture_output=True)
                    if parent_verify.returncode == 0:
                        run_command(["git", "meld", f"{oldest}^"])
                    else:
                        run_command(["git", "meld", "4b825dc642cb6eb9a001e5408d69288fbee4904f"])
                        
                    if untracked_files:
                        run_command(["git", "reset", "HEAD", "--"] + untracked_files)
            else:
                sort_res = run_command(
                    ["git", "log", "--no-walk", "--date-order", "--reverse", "--format=%H"] + hashes,
                    capture_output=True, text=True
                )
                sorted_hashes = sort_res.stdout.splitlines()
                if sorted_hashes:
                    oldest = sorted_hashes[0]
                    newest = sorted_hashes[-1]
                    parent_verify = run_command(["git", "rev-parse", "--verify", f"{oldest}^"], capture_output=True)
                    if parent_verify.returncode == 0:
                        run_command(["git", "meld", f"{oldest}^..{newest}"])
                    else:
                        run_command(["git", "meld", f"4b825dc642cb6eb9a001e5408d69288fbee4904f..{newest}"])

if __name__ == "__main__":
    main()
