#!/bin/bash

set -e

list-files -r -n 1000 ~/history/commits | xargs cat | {
    if [[ -t 1 ]] ; then
        hl '^    .*' '@cyan' \
        '^[^ ].*' '@yellow' \
        '\+(?=[+\-]*\s*$)' '@green' \
        '\-(?=[+\-]*\s*$)' '@red' |
        less --raw
    else
        cat
    fi
}

