#!/bin/bash

set -e
. mutil.sh

root=$(git root)
cd "$root"

branch="$1"
base=$(git upstream)
merge_base=$(git merge-base $base ${branch:-HEAD})

echo "Upstream: $base"
git branch -vv --list --color=always "$branch"
git diff --name-status $merge_base $branch
