#!/bin/bash

. mutil.sh

in-git -e || exit 2

root=$(git root)
cd "$root"

histfile="$HOME/cbin/temp/git-messages/$(date '+%Y-%m-%d/git-message-%H-%M-%S').txt"

pre_commit="$(git rev-parse HEAD 2>/dev/null)"

show_commit() {
    echo "# Directory: $(pwd)"
    echo "# Branch: $(git current-branch)"
    git show --no-patch | sed -e 's/^/# /; s/^#     //' # Remove the extra spaces in the message
}

print_description() {
    post_commit="$(git rev-parse HEAD 2>/dev/null)"

    commit="$(show_commit)"

    if [[ "$pre_commit" == "$post_commit" ]] ; then
        COLOR_OUT=2 bred "No commit made. The draft message was:"

        # It may be that git was interrupted. So let's print the draft file.
        cat "$(git rev-parse --git-dir)/COMMIT_EDITMSG"

    else
        COLOR_OUT=2 INFO "Message was:"
        echo "$commit"

        # Also copy to temp folder
        mkdir -p "${histfile%/*}"
        echo "$commit" > "$histfile"
        COLOR_OUT=2 INFO "Message copied to: "$histfile""
    fi
}

trap print_description EXIT

git commit "${@}"
rc=$?

INFO "Git commit finished with status $rc"

# print_description

exit $?
