#!/bin/bash

# Run "go build" for ARM and push under /data/local/tmp

set -e
. mutil.sh

file="$1"
basename="$(basename "$file" .go)"
out="/tmp/$basename"

GOARCH=arm ee go build -o "$out" "$file"
ls -l "$out"
ee arm-none-eabi-strip "$out"
ls -l "$out"

android-root
ee adb push "$out" "/data/local/tmp/$basename"
ee adb shell chmod +x "/data/local/tmp/$basename"
