#!/bin/bash

set -e
. mutil.sh

# sudo apt install sublime-text

distro=debian

if uname -a | grep -qi ubuntu ; then
  distro=ubuntu
fi

echo "Distro=$distro"

curl -fsSL https://download.docker.com/linux/$distro/gpg | sudo apt-key add -
echo sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$distro $(lsb_release -cs) stable"

sudo apt update

sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common \
    docker-ce \
    docker-ce-cli \
    containerd.io

sudo usermod -aG docker omakoto
