#!/bin/bash

set -e
. mutil.sh

# sudo apt install sublime-text

distro=$(lsb_release -is | tr 'A-Z' 'a-z')

echo "Distro=${distro:?Unknown distribution}"

curl -fsSL https://download.docker.com/linux/$distro/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$distro $(lsb_release -cs) stable"

sudo apt update

sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common \
    docker-ce \
    docker-ce-cli \
    containerd.io

sudo usermod -aG docker omakoto
