#!/bin/bash

# is-idle returns TRUE if the UI idle time is larger than $1 (default 60 seconds) in seconds.

threshold=${1:-60}

idle=0
if is-wayland ; then
    idle=$(dbus-send --print-reply --dest=org.gnome.Mutter.IdleMonitor /org/gnome/Mutter/IdleMonitor/Core org.gnome.Mutter.IdleMonitor.GetIdletime |
        sed -ne 's/^ *uint64 *//p')
else
    idle="$(xprintidle)"
fi

# if [[ -t 1 ]] ; then
#     echo "Idle: $(( $idle / 1000 ))"
# fi


(( "${idle:-0}" >= ( "$threshold" * 1000) ))
