#!/bin/bash

set -e

# Return true if the invoker is invoked from an interactive shell.

ppid() {
  local pid="$1"
  awk '{print $4}' /proc/$pid/stat
}

ppid=$(ppid $$)
pppid=$(ppid $ppid)

[[ $(cat /proc/$pppid/comm) == "lbash" ]]
