#!/bin/bash

set -e
. mutil.sh

# If running on WSL, convert given paths to the window paths.
# This doesn't use wslpath, which wouldn't convert nonexistent
# paths.

if ! iswsl ; then
  echo "$@"
  exit 0
fi

exist_only=0

eval "$(bashgetopt -u usage '
  e     exist_only=1            # Convert only when the file exists.
' "$@")"


for f in "$@" ; do
  if (( $exist_only )) && ! [[ -e "$f" ]] ; then
    echo "$f"
  else
    echo "\\\\wsl\$\\$(wsl-distro-name)$(abspath "$f" | tr '/' '\\')"
  fi
done
