#!/bin/bash

set -e
. mutil.sh

# If running on WSL, convert given paths to the window paths.
# This doesn't use wslpath, which wouldn't convert nonexistent
# paths.

if ! iswsl ; then
  echo "$@"
  exit 0
fi

exist_only=0
null_terminate=0

eval "$(bashgetopt '
  e     exist_only=1            # Convert only when the file exists.
  0     null_terminate=1        # Separate results with \0.
' "$@")"

for f in "$@" ; do
  if (( $exist_only )) && ! [[ -e "$f" ]] ; then
    echo -n "$f"
  else
    echo -n "\\\\wsl\$\\$(wsl-distro-name)$(abspath "$f" | tr '/' '\\')"
  fi
  if (( $null_terminate )) ; then
    perl -e 'print "\0"'
  else
    echo
  fi
done
