#!/bin/bash

# Set or print an android repo label.

#
# Usage:
#  label LABEL  # Set a label to current $ANDROID_BUILD_TOP
#  label -p [DIR] # Show the label for a dir.
#

#. minit.sh

if (( $# > 0 )) && [[ "$1" == "-p" ]]; then
    shift
    dir="${1:-$PWD}"
    cd "$dir"
    while [[ "$dir" != "/" ]] ;do
        if [[ -f "$DIR_LABEL_FILE" ]]; then
            cat "$DIR_LABEL_FILE"
            exit 0
        fi
        cd ..
        dir=$PWD
    done
    exit 0
fi

label="$*"

target="${ANDROID_BUILD_TOP:-}"

if [[ "$target" == "" ]] || ! [[ -d "$target" ]] ; then
    echo "Target dir not found" 1>2
    exit 1
fi

echo "$label" > "$target/$DIR_LABEL_FILE"
