#!/bin/bash

set -e
. mutil.sh

IFS=:
for dir in ${PATH} ; do
    for file in "$dir/"*; do
        if [[ -x "$file" ]] && [[ -f "$file" ]] ; then
            echo "$file"
        fi
    done
done | global-unique
