#!/bin/bash

# "Less + eXecute"
# Execute a given command and show the output with less.
# When less finishes, it'll re-execute the command and repeat.
#
# A command will be executed with the filter command, so the usual
# filters can be specified.

if (( $# == 0 )) ; then
  echo "$0: Missing command" 1>&2
  exit 1
fi

start-terminal bash -c "while true; do
{
  date
  filter $(shescape "$@")
} |& less -R ; done"
