#!/bin/bash

script="${0##*/}"

running=$(pgrep -f "bash .*$script")
if [[ "$(echo $running | wc -w)" -gt 1 ]] ; then
    echo "$script: Already running." 1>&2
    exit 1
fi

: ${target:='java .*/framework/metalava.jar '}
: ${max_targets:=2}
: ${interval:=0.5}
: ${debug:=0}

DEBUG() {
    if [[ $debug == 1 ]] ; then
        echo "$@"
        return 0
    fi
    return 1
}

DEBUG "Target: ${target@Q}"
DEBUG "Max processes: $max_targets"

function is_leaf() {
    local pid=$1
    ! pgrep -P $pid -f "$target" >/dev/null
}

while true; do
    DEBUG "Checking..."
    i=0
    for pid in $(pgrep -f "$target" | sort -n) ; do
        sig=STOP
        if [[ $i -lt $max_targets ]] && is_leaf $pid ; then
            sig=CONT
            i=$(( $i + 1 ))
        fi

        DEBUG kill -$sig $pid
        kill -$sig $pid

    done
    sleep $interval
done
