#!/bin/bash

script="${0##*/}"

running=$(pgrep -f "bash .*$script")
if [[ "$(echo $running | wc -w)" -gt 1 ]] ; then
    echo "$script: Already running." 1>&2
    exit 1
fi

: ${target:='java .*/framework/metalava.jar '}
: ${max_targets:=2}
: ${interval:=0.5}
: ${debug:=0}

DEBUG() {
    if [[ $debug == 1 ]] ; then
        echo "$@"
        return 0
    fi
    return 1
}

DEBUG \
"Target: ${target@Q}
Max processes: $max_targets"

while true; do
    DEBUG "Checking..."
    i=0
    for pid in $(pgrep -f "$target" | sort -n) ; do
        sig=STOP
        if [[ $i -lt $max_targets ]] ; then
            sig=COND
        fi

        DEBUG kill -$sig $pid

        i=$(( $i + 1 ))
    done
    sleep $interval
done
