#!/bin/bash

# Tells if we have interactive terminal (where we can directly launch man / fzf / etc),
# or we need to use term to create a new terminal.

if (( $NEEDS_TERM )) || is-in-agent; then
    exit 0
fi

if [[ ! -t 1 ]]; then
    exit 0
fi

exit 1
