#!/bin/bash

set -e

. mutil.sh

force=0
mode=--info
color=bcyan
print_to_term=1
wait=0
msgbox_opts=""
mobile=0
invocation_details=0

eval "$(getopt.pl -Nxd 'Show a dialog box' '
e|error|c|critical  mode=--error; color=bred; msgbox_opts=-e  # Show as error.
f|force             force=1                   # Obsolete option.
s|no-terminal       print_to_term=0           # Do not show the message on terminal.
w|wait              wait=1                    # Wait until the dialog closes.
m|mobile            mobile=1                  # Send mobile notification via pushover.
v|verbose           invocation_details=1      # Add invocation details.
' "$@")"

message="$*"

if (( $invocation_details )) ; then
  message="$message

Command: $(head -1 $(zenlog current-log))
Dir: ${PWD:-$(pwd)}
Host: $(hostname -f)"
fi

if (( $print_to_term )); then
  {
    echo
    $color -ui "$message"
    echo
  } 1>&2
fi

echo -ne '\007'
sleep 0.1
echo -ne '\007'
sleep 0.1
echo -ne '\007'
sleep 0.1
echo -ne '\007'

if (( $mobile )) ; then
  notify-mobile "$message"
fi

if isx ; then
  notify-send "[Message]" $'\n'"$message"
elif iswsl ; then
  msgbox $msgbox_opts "$message"
fi

if (( $wait )) ; then
  echo -n "Press enter to continue: "
  read
fi

exit 0
