#!/bin/bash

# Read from the clipboard, and try to fullpathify tokens
# using "recent-dirs", and use fzf to pick one(s)

set -e
. mutil.sh

files=$(cb | tr -s ' \t' '\n')

{
  recent-dirs | head -50 | while read -r dir ; do
    echo "$files" | while read -r file; do
      if [[ "$file" = /* ]] ; then
        # fullpath, just print
        echo "$file"
        continue
      fi
      full="$dir$file"
      if [[ -e "$full" ]] ; then
        echo "$full"
      fi
    done
  done
} | global-unique | fzf -m -0 -1 | shescapes
