#!/bin/bash

# Change DPI related settings depending on the environment
# Also update ~/.chromedpi too.


# exit 0 # Nothing to do on recent devices.


set -e
. mutil.sh

medir="${0%/*}"

if iswsl ; then
  echo "WSL detected. Not updating keymap." 1>&2
  exit 0
fi

sf=0
chrome_dpi=""
rdt_dpi=""

case "$(hostname -s)" in
  omakoto-glaptop2) # Dell laptop.
    # ee $medir/dell-keymap-custom
    # dell-touchscreen-enable 1
    chrome_dpi="2.6"
    # sf=2
    ;;
  x1c7u|debian) # X1 carbon gen7 / vmware
    chrome_dpi=""
    ;;
  x1c5deb|x1g5) # X1 carbon gen5
    chrome_dpi=""
    ;;
  x1eu|omakoto3) # X1 extreme / P1 gen 2
    chrome_dpi=""
    rdt_dpi="2"
    ;;
  surface) # Surface book 2, vmware
    chrome_dpi=""
    sf=2
    ;;
esac

if lsusb | grep -q '0853:0111' ; then # Topre keyboard.
  # $medir/dell-keymap-reset
  chrome_dpi=""
  rdt_dpi=""
  sf=1
  if hwinfo --monitor --short 2>/dev/null | grep -q T32p-20 ; then
    chrome_dpi="1.5"
  fi
fi

ee gsettings set org.cinnamon.desktop.interface scaling-factor $sf
echo "$chrome_dpi" > ~/.chromedpi
echo "$rdt_dpi" > ~/.remote-desktop-dpi

echo "Updated DPI settings."
