#!/bin/bash

# Change DPI related settings depending on the environment
# Also update ~/.chromedpi too.


# exit 0 # Nothing to do on recent devices.


set -e
. mutil.sh

medir="${0%/*}"

if iswsl ; then
  echo "WSL detected. Not updating keymap." 1>&2
  exit 0
fi

force=0
if [[ "$1" == "-f" ]] ; then
  force=1
fi


sf=2
chrome_dpi=""
rdt_dpi=""
font_size="" # Default
sound_device=""

case "$(hostname -s)" in
  nuc)
    exit 0 # Do nothing for NUC
    ;;
  omakoto-ct*)
    # sf=1
    if ! (( $force )) ; then
      echo "Skipping pc-config-update on cloudtop. Use [pc-config-update -f] to force run it." 1>&2
      exit 0
    fi
    chrome_dpi="1.2"
    sf=1
    ;;

  dell-vm*) # Dell windows desktop
    chrome_dpi="1.1"
    font_size=12
    sf=1
    ;;

  omakoto-glaptop2)
    # ee $medir/dell-keymap-custom
    # dell-touchscreen-enable 1
    chrome_dpi="2.6"
    # sf=2
    ;;
  x1nano-u|x1nano*|x1u-2024|x1nanou3)
    sf=1
    # chrome_dpi="1.5"
    ;;
  x1c7u|debian|x1gen12u) # X1 carbon gen7 / vmware
    chrome_dpi=""
    ;;
  x1c5deb|x1g5) # X1 carbon gen5
    chrome_dpi=""
    ;;
  x1eu|omakoto3) # X1 extreme / P1 gen 2
    chrome_dpi=""
    rdt_dpi="2"
    ;;
  surface) # Surface book 2, vmware
    chrome_dpi=""
    ;;
  x1yoga|omakoto-glaptop*) # X1 yoga, with gnome
    chrome_dpi="2.5"
    ;;
esac

if lsusb | grep -q -P '(0853:0111|K120|REALFORCE|Keychron)' ; then # Topre/Keychron keyboard.
  # $medir/dell-keymap-reset
  chrome_dpi=""
  rdt_dpi=""
  sf=1
  mon=/tmp/monitor.txt
  hwinfo --monitor --short 2>/dev/null > $mon
  if grep -q BDM4065 $mon ; then # Home monitor 40"
    chrome_dpi="1.2"
    font_size=13
    sf=1
  elif grep -q LNVTabExtreme $mon ; then # Lenovo tab extreme
    chrome_dpi="1.3"
    font_size=13
    sf=1
  elif grep -q "CSOT T3 LCD Monitor" $mon ; then # 18.5" FHD portable (bought in Japan)
    chrome_dpi="1"
    font_size=11
    sf=1
  elif grep -q CG437K $mon ; then # Home monitor 43"
    chrome_dpi="1"
    font_size=12
    sf=1
    # sound_device='alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink'
  elif grep -q -P '(T32p-20|U3223QE)' $mon ; then # Office monitor
    chrome_dpi="1.5"
  fi
fi

# ms-arc-mouse-natural-scroll.sh

# if false ; then
#   # For cinnamon
#   ee gsettings set org.cinnamon.desktop.interface scaling-factor $sf

#   # For gnome
#   # This actully isn't enough as of 2023-11-01, TODO Figure it out.
#   ee gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "[{'Gdk/WindowScalingFactor', <$sf>}]"
#   ee gsettings set org.gnome.desktop.interface scaling-factor $sf

#   $HOME/cbin/misc/linux-update-fonts $font_size

#   echo "Updated DPI settings."
# else
#   #chrome_dpi=1
#   rdt_dpi=1
# fi

echo "$chrome_dpi" > ~/.chromedpi
echo "$rdt_dpi" > ~/.remote-desktop-dpi

trackpoint-speedup.sh


if [[ "$sound_device" != "" ]] ; then
  ee pacmd set-default-sink "$sound_device"
fi

