#!/bin/bash

# Eat from stdin and show it on editor, and let the user "uncomment" lines
# Then print uncommented lines.
# If input contains only 1 line, just print it.

set -e
. mutil.sh

SCRIPT="${0##*/}"

temp=/tmp/$$.tmp
orig=$temp.orig

stdin="$(cat)"
if [[ -z $stdin ]] ; then
  echo "$SCRIPT: No input." 1>&2
  exit 1
fi

lines=$(echo "$stdin" | wc -l)
if (( $lines == 1 )) ; then
  echo "$stdin"
  exit 0
fi

# Read stdin and write temp with #
{
  echo '# Uncomment to select lines'
  echo "$stdin" | sed -e 's/^/#/'
} > $orig
cp $orig $temp

1w $temp

if diff -q $temp $orig >&/dev/null ; then
  echo "$SCRIPT: Nothing selected." 1>&2
  exit 1
fi

sed -e '/^#/d' $temp
exit 0
