#!/usr/bin/perl -w

# Copy STDIN to STDOUT, while showing the number of bytes transfered on STDERR.

use strict;

my $buf_size = 64;

my $size = 0;
my $buf = "";
my $rlen = 0;

while (($rlen = read(STDIN, $buf, $buf_size)) > 0) {
  print STDOUT $buf;

  $size += $rlen;
  printf STDERR ("\r%d", $size);

  for my $s (1024*1024, 256*1024, 16*1024, 1024) {
    if ($size >= $s) {
      $buf_size = $s;
      last;
    }
  }
}

print STDERR "\n";
