#!/usr/bin/env ruby

require_relative "./getopt"
require "shellhelper"

partial_token = true
expand_home = true

getopt(
  ["f|full-token", lambda { partial_token = false },
      "Get full token instead of partial token."],
  ["n|no-expand-home", lambda { expand_home = false },
      "Don't expand ~."],
  usage: "Print out the current readline token."
  );


command = ENV['READLINE_LINE']
pos = ENV['READLINE_POINT'].to_i

cmd = CommandLine.new(command, pos)

replaced = cmd.get_token(pos, partial_token)[2]

if expand_home
  replaced.sub!(/^ \~ (?= $ | \/) /x, ENV['HOME'])
end

puts unshescape(replaced)
