#!/usr/bin/perl -w

use strict;

while (defined(my $in = <>)) {
    chomp $in;
    print "$in\n";

    if ($in =~ m!^/!) {
        for my $key (sort keys %ENV) {
            next if $key =~ /^(:?PWD|OLDPWD|MY_ANDROID_ROOT|ANDROID_X_BUILD_TOP)$/; # Not interesting.

            my $val = $ENV{$key};
            next if ($val eq "");
            my $replaced = $in =~ s!^\Q$val\E!\${$key}!r;

            print "$replaced\n" if $replaced ne $in;
        }
    }
}
