#!/bin/bash

ndays=1

if [[ "$1" == "-n" ]] ;then
  ndays="$2"
  shift 2
fi

if (( $# == 0 )) ; then
  cat <<'EOF'

rg-today-log [-n NDAYS] [RG OPTIONS] QUERY

EOF
  exit 2
fi

today-logs -n $ndays | xargs rg "$@" /dev/null
