#!/bin/bash

set -e
. mutil.sh

quiet=0

if [[ "$1" == "-q" ]]; then
    quiet=1
fi


: ${DEVICE:=Wacom HID 527F Finger touch}

killall monitor-sensor >&/dev/null || true

update() {
    EE_QUIET=$quiet ee xinput set-prop "$DEVICE" 'Coordinate Transformation Matrix' "$@"
}

monitor-sensor | while read -r o ; do
    case "$o" in
    *bottom-up*)
        update -1 0 1 0 -1 1 0 0 1;;
    *normal*)
        update 1 0 0 0 1 0 0 0 1;;
    *right-up*)
        update 0 1 0 -1 0 1 0 0 1;;
    *left-up*)
        update 0 -1 1 1 0 0 0 0 1;;
    esac
    done
done
