#!/bin/bash

set -e
. mutil.sh

if (( $# < 2 )) ;then
  echo "Usage: $0 FROM-DIR TO-DIR" 1>&2
  exit 1
fi

#         -A, --acls                  preserve ACLs (implies -p)
#         -X, --xattrs                preserve extended attributes

ee time rsync ${DRY_RUN+--dry-run} -a --progress "${@}"
