#!/bin/bash

set -e
command="$1"

if [[ -z "$command" ]] ; then
  echo "Usage: runonce COMMAND [args...]" 1>&2
  exit 1
fi

# Note $HOME/tmp/ is a ramdisk
checkfile=$HOME/tmp/runonce_"${command##*/}_$(sha1sum <<<"$*" | awk '{print $1}')"

if [[ -f "$checkfile" ]] ; then
  exit 0
fi

"$@" && touch "$checkfile"
