#!/bin/bash

read w h < <( termsize )

if [[ "$1" == -u ]] ; then
  for (( x = 0 ; x < $w - 1 ; x+=2 )) ; do
    for (( y = 0 ; y < $h ; y++ )) ; do
      echo -n "あ"
    done
  done
else
  for (( x = 0 ; x < $w ; x++ )) ; do
    for (( y = 0 ; y < $h ; y++ )) ; do
      echo -n X
    done
  done
fi
