#!/bin/bash

set -e
. mutil.sh

file=$HOME/Downloads/screenshot-$(date8).png

echo "Select a window a drag a region."

# interactive, with borders
scrot -sb "$file"

echo "$file"
echo "$file" | cb
c "$file"
