#!/bin/bash

# Simple menu builder
#
# Example:
#
# case "$(select-menu '1: Run test only # comment' '2: Run with debugger'" in
#     1)
#         :
#         ;;
#     2)
#         :
#         ;;
#     *)
#         exit 1
# esac

(
    IFS=$'\n'
    echo "$*"
) |
hl '#.*$' '@333' |
fzf -1 --ansi | sed -e 's/:.*//'
