#!/bin/bash

# Simple menu builder
#
# Example:
#
# case "$(select-menu '1: Run test only # comment' '2: Run with debugger'" in
#     1)
#         :
#         ;;
#     2)
#         :
#         ;;
#     *)
#         exit 1
# esac


# If this worked, this would be a simpler way, but 
# this would always select the first item.
# keys="$( perl -e 'for $ch (ord('1')..ord('9'), ord('a')..ord('z'), ord('A')..ord('Z') ) { print(chr($ch), "\n") }' )"
# args+=("$i:clear-query+put(^)+put($i)+put(:)+accept-non-empty")


index=1
for item in "$@" ; do
    key=$(tr '[:upper:]' '[:lower:]' <<< ${item:0:1})
    args+=("--bind" "$key:pos($index)+accept-non-empty")
    index=$(( index + 1 ))
done

(
    IFS=$'\n'
    echo "$*"
) |
hl '#.*$' '@333' |
fzf -1 --ansi "${args[@]}" | sed -e 's/^\(.\).*/\1/'
