#!/usr/bin/perl -w

use strict;

sub escape($) {
  my ($arg) = @_;
  if ( $arg =~ /[^a-zA-Z0-9\-\.\_\/\:\+\@]/ ) {
      return("'" . ($arg =~ s/'/'\\''/gr) . "'"); #/
  } else {
      return($arg);
  }
}

# If executed as "shescapes", escape input from stdin
if ($0 =~ /s$/) {
  while (<>) {
    chomp;
    print(escape($_), "\n");
  }
  exit 0
}

my $sep = "";
for my $arg ( @ARGV ) {
    print $sep;
    print escape($arg);
    $sep = " ";
}

# If executed as "shescapen", then don't print newline.
if ($0 !~ /n$/) {
    print "\n";
}
