#!/bin/bash

# Take PIDs from the command line, and print the command line of these proceses.
#
# Example: show-commandline $(pgrep java)


for pid in "${@}"; do
    echo "# Pid: $pid"
    indent=""
    
    tokens=()
    while IFS= read -r -d $'\0' token; do
        tokens+=("$token")
    done < /proc/$pid/cmdline

    pretty-commandline "${tokens[@]}"
done
