#!/bin/bash

# Take PIDs from the command line, and print the command line of these proceses.
#
# Example: show-commandline $(pgrep java)


for pid in "${@}"; do
    echo "# Pid: $pid"
    indent=""
    
    # Read null-delimited tokens and envs from /proc files
    readarray -d '' -t tokens < /proc/$pid/cmdline
    readarray -d '' -t envs < /proc/$pid/environ

    for env in "${envs[@]}" ; do
        name="${env%%=*}"
        value="${env#*=}"
        if [[ "${!name}" == "$value" ]]; then
            #echo -n "# "
            continue
        fi

        printf "export %s=%q\n" "$name" "$value"
    done
    echo
    pretty-args "${tokens[@]}"
done
