#!/bin/bash

host=172.20.201.21
port=22

if ! in-home-network ; then
    host=omakoto.net
    port=10022
fi

if [[ "$1" == "-p" ]] ; then
    echo $port
elif [[ "$1" == "-h" ]] ; then
    echo $host
elif [[ "$1" == "-u" ]] ; then
    echo omakoto
else
    echo $host:$port
fi
