#!/bin/bash

set -e
. mutil.sh

base=$HOME/sshfs/

mkdir -p $base/{pi1,pi3,pi0,piz1,pi9}

function mount() {
  local server="$1"
  local mp="$2"
  if df -t fuse.sshfs "$mp" >&/dev/null; then
    return 0 # already mounted
  fi
  ee sshfs "$server" "$mp"
}

#mount pi@172.20.201.1:/ $base/pi1
#mount pi@172.20.201.3:/ $base/pi3
mount omakoto@172.20.201.9:/ $base/pi9
mount omakoto@172.20.201.10:/ $base/piz1
