#!/bin/bash

set -e
. mutil.sh

port=8080

function provide_content() {
  echo 'HTTP/1.0 200'
  echo 'content-type: text/plain'
  echo
  while true; do
    date '+%Y-%m-%d %H:%M:%S'
    sleep 1
  done
}

function do_server() {
  provide_content | nc -l $port
}

while true; do
  echo "Listening on http://127.0.0.1:$port/ ..."
  do_server
done
