#!/bin/bash

set -e
export GO_RUNNER_SKIP_GEN=1

cd "${0%/*}"
script="./timergo/timer.go"

if (( $RUNNER_SHOW_MAIN )) ; then
    echo "$(readlink -f "$script")"
    exit 0
fi

exec go run "$script" "${@}"
