#!/bin/bash

set -e
. mutil.sh

addr=$(hostname -I | a1)
port=8080

function provide_content() {
  echo 'HTTP/1.0 200'
  echo 'content-type: text/plain'
  echo
  while true; do
    date '+%Y-%m-%d %H:%M:%S'
    sleep 1
  done
}

function do_server() {
  provide_content | nc -l $addr $port
}

while true; do
  echo "Listening on http://$addr:$port/ ..."
  do_server
done
