#!/bin/bash

# Switch the keymap depending on the device and the connected keyboard.

# Also update ~/.chromedpi too.

set -e
. mutil.sh

medir="${0%/*}"


chrome_dpi=""

case "$(hostname -s)" in
  omakoto-glaptop) # Dell laptop.
    if lsusb | grep -q '0853:0111' ; then # Topre keyboard.
      ee $medir/dell-keymap-reset
      chrome_dpi="1.5"
      gsettings set org.cinnamon.desktop.interface scaling-factor 1
    else
      ee $medir/dell-keymap-custom
      chrome_dpi="$CHROME_DPI"
      gsettings set org.cinnamon.desktop.interface scaling-factor 2
    fi
    ;;
  *)
    ee keymap-reset
    ;;
esac

echo "$chrome_dpi" > ~/.chromedpi

echo "Updated keymap."
