#!/bin/bash

# Switch the keymap depending on the device and the connected keyboard.

# Also update ~/.chromedpi too.

set -e
. mutil.sh

medir="${0%/*}"

if iswsl ; then
  echo "WSL detected. Not updating keymap." 1>&2
  exit 0
fi

chrome_dpi="1.5"
rdt_dpi=1.0

case "$(hostname -s)" in
  omakoto-glaptop2) # Dell laptop.
    if lsusb | grep -q '0853:0111' ; then # Topre keyboard.
      ee $medir/dell-keymap-reset
      gsettings set org.cinnamon.desktop.interface scaling-factor 1
    elif lsusb | grep -q '05e3:0610' ; then # UK rental display
      ee $medir/dell-keymap-reset
      gsettings set org.cinnamon.desktop.interface scaling-factor 2
    else
      ee $medir/dell-keymap-custom
      chrome_dpi="2.6"
      rdt_dpi=1.5
      gsettings set org.cinnamon.desktop.interface scaling-factor 2
    fi
    dell-touchscreen-enable 1
    ;;
  *)
    ee keymap-reset
    ;;
esac

echo "$chrome_dpi" > ~/.chromedpi
echo "$rdt_dpi" > ~/.remote-desktop-dpi

echo "Updated keymap."
