#!/usr/bin/perl
# imv - Interactive file and directory renamer using a text editor.
# This script allows editing directory contents or a list of files in a text editor
# to rename, copy, or delete them.

use v5.36;
use utf8;

our $VERSION = '0.040-woldrich-modern';

use File::Basename;
use File::Spec;
use File::Temp;
use File::Copy;
use File::Path ();
use Getopt::Long;

my $error = 0;
my $verbose = 1;
my $help = 0;
my $expression = "";
my $fullpath = 0;

sub print_help() {
  print <<'EOF';
imv - Interactive directory/file renamer using a text editor

Usage:
  imv [options] [directory|file|-]

Description:
  imv (also known as vidir) allows you to edit the contents of a directory
  or a list of files using your favorite text editor.

  Each item appears on a numbered line. You can:
  - Edit the filenames to rename files.
  - Delete lines to remove files/directories (after confirmation).
  - Swap the numbers of two files to swap their filenames.
  - Duplicate a line (keep the number) to copy a file.

  If no directory or file is specified, the current directory is edited.
  If '-' is specified, a list of filenames is read from standard input.

Options:
  -e, --expression EXP   Run a Perl expression on each filename before editing.
                         The filename is in $_ and can be modified.
  -f, --fullpath         Use the full (absolute) path for each filename without resolving symlinks.
  -v, --verbose          Verbosely display the actions taken by the program (default).
  -h, --help             Show this help message.

Examples:
  # Edit the current directory
  imv

  # Edit the current directory showing absolute paths (without resolving symlinks)
  imv -f

  # Edit only JPEG files in the current directory
  imv *.jpeg

  # Rename file extensions from .htm to .html using -e
  imv -e 's/\.htm$/\.html/' *.htm

  # Convert all filenames in the current directory to lowercase using -e
  imv -e '$_ = lc($_)' *

  # Replace spaces with underscores in all filenames in the current directory using -e
  imv -e 's/\s+/_/g' *

  # Prepend a prefix to all files using -e
  imv -e '$_ = "prefix_" . $_' *

  # Find all files recursively and edit their names
  find -type f | imv -
EOF
}

GetOptions(
  "verbose|v"      => \$verbose,
  "expression|e=s" => \$expression,
  "fullpath|f"     => \$fullpath,
  "help|h"         => \$help,
) or do {
  print_help();
  exit 1;
};

if ($help) {
  print_help();
  exit 0;
}

sub copyp($from, $to) {
  return system("/bin/cp", "-n", "--preserve=mode,links", "-P", $from, $to) == 0;
}

my(@files, @directories, @sorted);
@ARGV = @ARGV > 0 ? @ARGV : './';

for my $item(@ARGV) {
  if($item eq '-') {
    push(@files, map { chomp; $_ } <STDIN>);
    close STDIN or die "Cant close STDIN: $!\n";
    open(STDIN, '/dev/tty') or die "Cant reopen STDIN: $!\n";
    next;
  }
  if(-d $item) {
    opendir(my $dh, $item) or die "Cant opendir $item: $!\n";
    for(grep { ! /\A[.]{1,2}\Z/ } readdir($dh)) {
      $item =~ s{/$}{};
      if(-d "$item/$_") {
        push(@directories, "$item/$_/");
      }
      else {
        push(@files, "$item/$_");
      }
    }
    closedir $dh or die "Cant close dirhandle $item: $!\n";
    next;
  }
  if(-e $item) {
    push @files, $item;
    next;
  }
  die "Invalid item: '$item'\n";
}

@sorted = (sort(@directories), sort(@files));

if ($fullpath) {
  @sorted = map {
    my $has_slash = m{/\z} ? '/' : '';
    File::Spec->rel2abs($_) . $has_slash;
  } @sorted;
}

if (grep(/[[:cntrl:]]/, @sorted)) {
  die "$0: control characters in filenames are not supported\n";
}

my $tmp=File::Temp->new(TEMPLATE => "dirXXXXX", DIR => File::Spec->tmpdir);
open (my $out_fh, ">", $tmp->filename) || die "$0: cannot create ".$tmp->filename.": $!\n";

my %item;
my %done;
my $c=0;
foreach (@sorted) {
  $item{++$c}=$_;
  my $was = $_;
  if ($expression) {
    eval $expression;
    die "$0: expression error: $@\n" if $@;
    if ($was ne $_) {
      print $out_fh "##    $was ->\n";
    }
  }
  print $out_fh sprintf("%5d %s", $c, $_);
  print $out_fh ("\t## -> ", readlink $_) if -l $_;
  print $out_fh "\n";
}
@sorted=();
close $out_fh || die "$0: cannot write ".$tmp->filename.": $!\n";

my @editor = 'vi';

if(exists($ENV{VIDIR_EDITOR})) {
  @editor = $ENV{VIDIR_EDITOR};
}
elsif(exists($ENV{EDITOR})) {
  @editor = split(' ', $ENV{EDITOR});
}
elsif(-x '/usr/bin/editor') {
  @editor = '/usr/bin/editor';
}
elsif(exists($ENV{VISUAL})) {
  @editor = split(' ', $ENV{VISUAL});
}

sub readall($file) {
  open(my $fh, '<', $file) or die("Error: $!\n");
  my $data;
  read($fh, $data, -s $file );
  close $fh;
  return $data;
}

sub confirm($msg) {
  print $msg, "[y/N] ";
  my $answer = <STDIN>;
  return ($answer =~ /^y/);
}

my $pre = readall($tmp->filename);

if( (exists($ENV{VIDIR_EDITOR_ARGS})) && ($ENV{VIDIR_EDITOR_ARGS} ne '') ) {
  system(@editor, $ENV{VIDIR_EDITOR_ARGS}, $tmp);
}
else {
  system(@editor,  $tmp);
}

my $now = readall($tmp->filename);

if ($pre eq $now) {
  print STDERR "File unchanged.\n";
  if ($expression) {
    exit 1 unless confirm "Proceed? ";
  } else {
    exit 1;
  }
}

open (my $in_fh, "<", $tmp->filename) || die "$0: cannot read ".$tmp->filename.": $!\n";
while (<$in_fh>) {
  chomp;
  s/\s*\#\#.*$//;
  if(/^\s*(\d+)\s+(.*)/) {
    my $num=int($1);
    my $name=$2;
    my $iscopy=exists $done{$num};
    #$name =~ s{/+$}{}g;
    if (! exists $item{$num} && ! $iscopy) {
      die "$0: unknown item number $num\n";
    }
    elsif ($iscopy || $name ne $item{$num}) {
      next unless length $name;
      my $src=$iscopy ? $done{$num} : $item{$num};

      if (! (-e $src || -l $src) ) {
        print STDERR "$0: $src does not exist\n";
        delete $item{$num};
        next;
      }

      # deal with swaps
      if (-e $name || -l $name) {
        my $backup_name = $name . "~";
        my $suffix = 0;
        while (-e $backup_name || -l $backup_name) {
          $suffix++;
          $backup_name = $name . "~" . $suffix;
        }
        if (! rename($name, $backup_name)) {
          print STDERR "$0: failed to rename $name to $backup_name: $!\n";
          $error=1;
        }
        elsif ($verbose) {
          print "'$name' -> '$backup_name'\n";
        }
        foreach my $item (keys %item) {
          if ($item{$item} eq $name) {
            $item{$item} = $backup_name;
          }
        }
      }

      File::Path::make_path(dirname($name));
      my $result=$iscopy ? copyp($src, $name) : move($src, $name);
      if (! $result) {
        print STDERR "$0: failed to ".($iscopy ? "copy" : "rename")." $src to $name: $!\n";
        $error=1;
      }
      if (-d $name && ! $iscopy) {
        foreach (values %item) {
          s/^\Q$src\E/$name/;
        }
      }
      if ($verbose) {
        print "'$src' => '$name'\n" unless $iscopy;
        print "'$src' ~> '$name'\n" if $iscopy;
      }
    }
    $done{$num}=$name;
    delete $item{$num};
  }
  elsif (/^\s*$/) {
    # skip empty line
  }
  else {
    die "$0: unable to parse line \"$_\", aborting\n";
  }
}
close $in_fh || die "$0: cannot read ".$tmp->filename.": $!\n";
unlink($tmp.'~') if -e $tmp.'~';

sub rm($file) {
  if (-d $file && ! -l $file) {
    return File::Path::rmtree($file);
  }
  else {
    return unlink $file;
  }
}

foreach my $item (reverse sort values %item) {
  next unless confirm "Remove $item? ";
  if (! rm($item)) {
    print STDERR "$0: failed to remove $item: $!\n";
    $error=1;
  }
  if ($verbose) {
    print "removed '$item'\n";
  }
}

exit $error;

__END__

=head1 NAME

imv - edit directory / rename files using a text editor

=head1 SYNOPSIS

B<imv> [--verbose] [-e EXPRESSION] [-f] [directory|file|-] ...

=head1 DESCRIPTION

imv (adapted from vidir) allows editing of the contents of a directory in a text
editor. If no directory is specified, the current directory is edited.

When editing a directory, each item in the directory will appear on its own
numbered line. These numbers are how imv keeps track of what items are
changed. Delete lines to remove files from the directory, or
edit filenames to rename files. You can also switch pairs of numbers to
swap filenames.

Note that if "-" is specified as the directory to edit, it reads a list of
filenames from stdin and displays those for editing. Alternatively, a list
of files can be specified on the command line.

=head1 OPTIONS

=over 4

=item -e, --expression EXPRESSION

Specify a Perl expression to run on each filename. The filename is stored in $_
and can be modified.

=item -f, --fullpath

Use the full (absolute) path for each filename without resolving symlinks.

=item -v, --verbose

Verbosely display the actions taken by the program.

=item -h, --help

Show the help message.

=back

=head1 EXAMPLES

=over 4

=item imv

=item imv -f

Edit the current directory using absolute paths.

=item imv *.jpeg

Typical uses.

=item imv -e 's/\.htm$/\.html/' *.htm

Rename file extensions from .htm to .html.

=item imv -e '$_ = lc($_)' *

Convert all filenames in the current directory to lowercase.

=item imv -e 's/\s+/_/g' *

Replace spaces with underscores in all filenames in the current directory.

=item imv -e '$_ = "prefix_" . $_' *

Prepend a prefix to all files.

=item find | imv -

Edit subdirectory contents too. To delete subdirectories,
delete all their contents and the subdirectory itself in the editor.

=item find -type f | imv -

Edit all files under the current directory and subdirectories.

=back

=head1 ENVIRONMENT VARIABLES

=over 4

=item EDITOR

Editor to use.

=item VISUAL

Also supported to determine what editor to use.

=item VIDIR_EDITOR_ARGS

Optional args for editor

=back

=head1 AUTHOR

Joey Hess <joey@kitenet.net> 2006-2010

Modifications by Magnus Woldrich  <m@japh.se> 2011

=head1 COPYRIGHT

Copyright 2006-2011 the B<vidir> L</AUTHOR>s as listed above.

Licensed under the GNU GPL.

=cut
