#!/bin/bash

set -e
. mutil.sh

eol_opts=""

eval "$(bashgetopt '
  0     eol_opts=-0        # Separate results with \0.
' "$@")"


for f in "$@" ; do
  echo /mnt/"$(perl -pe 's!\\!/!g ; s!:!!g; $_ = lc ' <<< "$f")"
  print-eol $eol_opts
done
