#!/bin/bash

set -e

SCRIPT_DIR="${0%/*}"

run() {
    echo "Running: $@"
    "$@"
}

cat <<'EOF'
If the following command requires the root password, add the
following line to /etc/sudoers:
```
%sudo ALL=NOPASSWD: /etc/rc2.d/S01ssh
```
EOF
run sudo /etc/rc2.d/S01ssh start
run $SCRIPT_DIR/wsl-update-hosts

if [[ -n "WSL_DISTRO_NAME" ]] ; then
    run bash -c "echo $WSL_DISTRO_NAME > $HOME/.wsl-distro-name"
fi
