#!/bin/bash

set -e

SCRIPT_DIR="${0%/*}"

PATH="$PATH:$SCRIPT_DIR"

if [[ -z "$WSL_DISTRO_NAME" ]] ; then
    echo "Not on WSL" 1>&2
    exit 1
fi

hosts_win='c:\windows\system32\drivers\etc\hosts'
hosts=$(w2l "$hosts_win")
temp=/tmp/hosts-temp-$$.txt

tag="#WSL:${WSL_DISTRO_NAME?}"

sed -e "/${tag}/d" "$hosts" > "$temp"
echo "$(local-ipv4-address) ${WSL_DISTRO_NAME?}.wsl $tag" >> "$temp"
if ! cp "$temp" "$hosts" ; then
  echo "Give 'full control' to users!"
  explorer.exe "${hosts_win%\\*}\\"
fi

rm -f "$temp"
