#!/bin/bash

set -e

SCRIPT_DIR="${0%/*}"

run() {
    echo "Running: $@"
    "$@"
}

cat <<'EOF'
If the following command requires the root password, run the following
command:
```
(echo '%sudo ALL=NOPASSWD: /etc/rc2.d/S01ssh' |
  sudo tee /etc/sudoers.d/sshd) && sudo chmod 0440 /etc/sudoers.d/sshd
```
EOF
run sudo /etc/rc2.d/S01ssh start
run $SCRIPT_DIR/wsl-update-hosts

if [[ -n "WSL_DISTRO_NAME" ]] ; then
    run bash -c "echo $WSL_DISTRO_NAME > $HOME/.wsl-distro-name"
fi
