#!/bin/bash

# Copy the output of the last 10 commands to the clipboard.

set -e

. <(zenlog -s)

num_commands=10
copy=0
raw=""
open=0
single=0
reverse=cat
no_command=0
viewer="1 -e"

eval "$(getopt.pl -Nd 'Cat last N command output' "
n: num_commands=%     # Specify number of commands.
c copy=1              # Copy to clipboard.
r raw=1               # Copy raw text.
o open=1              # Open with 1.
s single=1            # Only show a single command log.
R reverse=tac         # Reverse order (newer fast).
t no_command=1        # Content only (no command line).
" "$@")"

if (( $raw )) ; then
  viewer=c
fi

if (( $num_commands == 1 )) ; then
  single=1
fi

files=$(zenlog history ${raw:+-r} | tail -$num_commands | $reverse | {
  if (( $single )) ; then
    head -1
  else
    cat
  fi
}
)

# Basically cat, but makes sure the last line of each file
# ends with LF.
cat_lf() {
  perl -we '
#line 50
use strict;
for my $f (@ARGV) {
  my $last;
  open my $in, "<", $f or die "Cannot open $f: $!\n";
  while (defined(my $line = <$in>)) {
    print $line;
    $last = $line;
  }
  print "\n" unless $last =~ /\n$/;
  close $in;
}

' "${@}"
}

if (( $no_command )) ; then
  tmpfile=/tmp/$(date8)-$$-zenlog-contents.txt
  for n in $files ; do
    sed -e '1d' "$n"
  done > $tmpfile
  files=$tmpfile
fi

if (( $copy )) ; then
  cat_lf $files | cb -q
  if (( $single )) ; then
    echo "[Copied command log to clipboard]" 1>&2
  else
    echo "[Copied last $num_commands command log to clipboard]" 1>&2
  fi
fi

if (( $open )) ; then
  if (( $single )) ; then
    echo "[Opening command log]" 1>&2
    $viewer $files >& /dev/null
  else
    echo "[Opening last $num_commands command log]" 1>&2
    cat_lf $files | $viewer >& /dev/null
  fi
  exit 0
fi

cat_lf $files
